rcbops/rpc-maas

rabbitmq_status.py

Adding rabbitmq channels check as per #138

Adding rabbitmq channels check as per #138

---

README.md
cinder_api_local_check.py
galera_check.py
glance_api_local_check.py
horizon_check.py
keystone_api_local_check.py
memcached_status.py
neutron_api_local_check.py
nova_api_local_check.py
rabbitmq_status.py

Where a metric is a numerical (non boolean) value, we add a descriptive unit to be displayed with the metric
closes: #142

add units to all numerical metrics

---

rabbitmq_status.py

Check that rabbitmq connections don't have multiple channels

Add rabbitmq channels check

---

cinder_api_local_check.py
glance_api_local_check.py
glance_registry_local_check.py
heat_api_local_check.py
keystone_api_local_check.py
neutron_api_local_check.py
nova_api_local_check.py
nova_api_metadata_local_check.py
service_api_local_check.py

We are dealing w/ floats here so the metric type needs to be updated
accordingly.
Closes #106
(cherry picked from commit b50a91b132b41b07457095d28516f26358b7dc1a)
Conflicts:
README.md

Change uint32 ms types to double

---

memcached_status.py

Closes https://github.com/rcbops/rpc-maas/issues/152

Fix issues w/ memcached_status.py

---

cinder_service_check.py
neutron_service_check.py
nova_service_check.py

Removes the positional argument validation as IPv4 address and updates
help messages.
Fixes #157

Accept DNS hostname or IP address as API host target

---

nova_api_local_check.py

Fixes #179
(cherry picked from commit 9d87e1fd3079e0099e38de543d01f66a05cbe876)

Fixing  nova_api_local_check.py reports useless active/error/... metrics

---

README.md

Adds hostname as flavor of required parameter.
Fixes #184

Update README section for service checks

---

disk_utilisation.py

Backport fix for #177

---

elasticsearch_query.py

This is a simple monitor script that runs the provided elasticsearch query and reports how many hits were found.

elasticsearch query monitor

---

defaults/main.yml
files/plugins/maas_common.py
files/plugins/nova_cloud_stats.py
files/plugins/process_check_container.py
files/plugins/process_check_host.py
tasks/maas_host_install.yml

This fix updates the maas plugins to be able to be run with the upstream constraints
for novaclient and psutil.
Connects rcbops/u-suk-dev#1642

Fixes MaaS for Ocata SHA

---

README.rst

All issues should be reported to the rpc-openstack repository

Add issue tracking location

---

tasks/raxmon_agent_install.yml

Updates {{ maas_plugin_dir }} to {{ maas_source_plugin_dir }} in stable/kilo. 
Fixes: #261

Install MAAS Plugins fix

---

defaults/main.yml
templates/container_storage_checks.yaml.j2
templates/hp-check.yaml.j2

Remove maas_plugin_dir and references within templates.
Fixes: #266

Remove maas_plugin_dir variable and template references

---

defaults/main.yml
templates/container_storage_checks.yaml.j2
templates/hp-check.yaml.j2

Update container_storage_checks.yaml.j2 to remove venv wrapper in stable/kilo.
Fixes: #264

Remove maas_plugin_dir and fix associated templates

---

playbooks/maas-ceph-mon.yml
playbooks/maas-ceph-osd.yml
playbooks/maas-ceph-raxmon.yml

Add task to drop the ceph keyring on the osds nodes as it's needed by the ceph_osd_stats check.

Drop keyring file on osds

---

playbooks/maas-openstack-swift.yml

Limit which proxy host the set fact url task is run against.

limit similarly to previous tasks

---

playbooks/templates/rax-maas/swift_account_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_async_check.yaml.j2
playbooks/templates/rax-maas/swift_container_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_md5_check.yaml.j2
playbooks/templates/rax-maas/swift_object_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_quarantine_check.yaml.j2
playbooks/templates/rax-maas/swift_time_sync_check.yaml.j2

Restrict swift-recon checks to 2 nodes at once

---

playbooks/files/rax-maas/tools/rpc-maas-tool.py
playbooks/library/raxmon.py
playbooks/maas-verify.yml
playbooks/vars/maas-agent.yml
playbooks/vars/main.yml
run-tests.sh
test-requirements.txt
tests/aio-create.sh
tests/maasutils.py
tests/test-ansible-functional.sh
tests/user_liberty_vars.yml
tests/user_mitaka_vars.yml
tests/user_newton_vars.yml
tox.ini

If the gate job passes in the proper creds the test script will react
and enable the maas API checks.
Related: rcbops/rpc-gating#268
Related: rcbops/rpc-gating#273

Test the maas API in the gate

---

doc/source/usage.rst
playbooks/files/tigkstack/grafana-panels/dynamic.json.j2
playbooks/files/tigkstack/grafana-panels/network.json
playbooks/files/tigkstack/grafana-panels/summary.json
playbooks/files/tigkstack/grafana-panels/system.json
playbooks/maas-tigkstack-grafana.yml
playbooks/maas-tigkstack-telegraf.yml
playbooks/templates/tigkstack/grafana.ini.j2
playbooks/templates/tigkstack/grafana_influx_connection.json.j2
playbooks/templates/tigkstack/telegraf.conf.j2
playbooks/vars/maas-tigkstack.yml
tests/rpcm_influx_hosts.yml.env
tests/test-ansible-functional.sh
tests/user_rpcm_secrets.yml

This change adds a grafana playbook to the system and pulls
with it the creation of dashboard panel(s).

added grafana playbook

---

bindep.txt
playbooks/files/tigkstack/grafana-panels/dynamic.json.j2
playbooks/library/_uri.py
playbooks/library/raxmon.py
playbooks/maas-tigkstack-grafana.yml
playbooks/templates/tigkstack/grafana.ini.j2
playbooks/templates/tigkstack/grafana_influx_connection.json.j2
playbooks/vars/maas-tigkstack.yml
playbooks/vars/maas-ubuntu.yml
test-requirements.txt
tests/test-ansible-functional.sh
tox.ini

The constraints needed in the test repo need to be updated to ensure
pyrax works 100% of the time.
The URI module in early versions of Ansible is broken. To fix this the
URI module has been vendored to ensure that it will always work for our
limited needs. To allow this module to work its using the deprecated
syntax such that it will not conflict with the actual URI module as
provided by Ansible.

Add additional constraints and vendor URI

---

playbooks/files/pip-constraints.txt
playbooks/files/rax-maas/plugins/README.md
playbooks/files/rax-maas/plugins/ironic_api_local_check.py
playbooks/files/rax-maas/plugins/maas_common.py
playbooks/maas-openstack-all.yml
playbooks/maas-openstack-ironic.yml
playbooks/templates/rax-maas/ironic_api_local_check.yaml.j2
playbooks/templates/rax-maas/lb_api_check_ironic_api.yaml.j2
playbooks/vars/maas-openstack.yml

This commit adds local and remote Ironic API monitoring to Rackspace MaaS.

Add local and remote Ironic API monitoring

---

.gitignore
playbooks/files/rax-maas/plugins/README.md
playbooks/files/rax-maas/plugins/ironic_capacity_check.py
playbooks/maas-openstack-ironic.yml
playbooks/templates/rax-maas/ironic_api_local_check.yaml.j2
playbooks/templates/rax-maas/ironic_capacity_check.yaml.j2
playbooks/vars/maas-openstack.yml

Turtles 106 ironic capacity check

---

tests/aio-create.sh
tests/user_ceph_vars.yml

Add Ceph scenario to rpc-maas

---

tests/aio-create.sh

Add pike test checkout

---

playbooks/maas-verify.yml
playbooks/vars/main.yml
tests/test-ansible-functional.sh

These commits fix a few issues discovered while using maas-verify for checking on phobos.

RE-645 rpc-maas fixes for Phobos Verification

---

playbooks/files/rax-maas/plugins/hp_monitoring.py

HP has begun replacing the hpssacli package with ssacli.
The arguments and output format are still the same,
requring minimal effort to make this change.
The HP MCP version is managed as part of the openstack-ops module
and is now frozen to version 10.6 to better synchronize these changes
Closes-Bug: RO-3090

Use the new HP ssacli over hpssacli

---

playbooks/maas-tigkstack-grafana.yml
playbooks/maas-tigkstack-influxdb.yml
playbooks/maas-tigkstack-telegraf.yml
playbooks/maas-verify.yml

Addressing ansible-lint errors within maas-tigkstack and verify

Fixing ansible linting errors

---

tests/aio-create.sh
tox.ini

Pin requirements and fix tox

---

tests/aio-create.sh

Remove pinned requirement

---

playbooks/maas-openstack-octavia.yml
playbooks/templates/rax-maas/lb_api_check_octavia.yaml.j2

K8S-545 Octavia MaaS addendum

---

playbooks/files/rax-maas/plugins/README.md
playbooks/files/rax-maas/plugins/neutron_ovs_agent_check.py
playbooks/maas-openstack-neutron.yml
playbooks/templates/rax-maas/neutron_ovs_agent_check.yaml.j2

1. Take into consideration of running on compute node
2. Add alarms for ovsdb-server and ovs-vswitchd

TURTLES-354: Improvement on neutron OVS agent check script.

---

playbooks/files/rax-maas/plugins/octavia_check_quota_limits.py
playbooks/maas-openstack-octavia.yml
playbooks/templates/rax-maas/octavia_quota_check.yaml.j2
playbooks/vars/maas-openstack.yml

Only Compute and Volume support quota limt checks so Octavia
will check those and add checks for network once this info
becomes available on Pike.

Adds quota check for Octavia

---

playbooks/maas-managed-k8.yml
playbooks/templates/rax-maas/managed_k8_api_local_check.yaml.j2
playbooks/vars/maas-managed-k8.yml

- the server listens on 8890 instead of 8090
- we should use the internal_vip

Fixes auth server URL

---

playbooks/files/rax-maas/plugins/rally_performance.py

This change adds a class to manage plugin configuration in preparation for more
steps in the plugin relying on configuration read from a file.

TURTLES-645: Load maas_rally plugin configuration via class

---

playbooks/files/rax-maas/plugins/glance_registry_local_check.py
playbooks/templates/rax-maas/glance_registry_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local glance api check.
Another commit for #TURTLES-313
Signed-off-by: Michael Rice <michael.rice@rackspace.com>

TURTLES-313 update glance_registry_local_check to support ssl

---

playbooks/files/rax-maas/plugins/glance_api_local_check.py
playbooks/templates/rax-maas/glance_api_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local glance api check.
Another commit for #TURTLES-313

TURTLES-313 update glance_local_api_check to support ssl

---

playbooks/templates/rax-maas/swift_account_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_container_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_object_replication_check.yaml.j2
releasenotes/notes/fix-rate-functions-6c30e91bdb5931df.yaml

Remove division by check period in rate functions across all templates.

Fix rate functions 

---

playbooks/maas-infra-rabbitmq.yml
playbooks/maas-tigkstack-grafana.yml
releasenotes/notes/fix-pip-10-348e9727569cbcd7.yaml
tests/aio-create.sh
tests/test-ansible-functional.sh

1.  Pin pip to upstream restrictions.
2.  Add `no_log: True` to comply OSA linting.
3. Pin SecretStorage to Python 2 compatible version. see details [here](https://github.com/mitya57/secretstorage).

Fixing maas gate failure.

---

playbooks/files/rax-maas/plugins/openmanage.py
releasenotes/notes/add_support_for_dell_14g-3cccc67072dd5072.yaml

Adds support for 9.1.0 of Open Manage for Dell 14G.
http://linux.dell.com/repo/community/openmanage/
http://topics-cdn.dell.com/pdf/dell-openmanage-software-9.1_support-matrix_en-us.pdf

FLEEK-42 Add support for Open Manage 9.1.0 for Dell 14G

---

gating/post_merge_test

To allow periodic tests to run, we symlink the
PM test folder to the PR test folder.

RE-1463 Add gating/post_merge_test

---

playbooks/templates/tigkstack/influxdb.conf.j2
playbooks/vars/maas-tigkstack.yml
releasenotes/notes/RO-4251-override-influxdb_max_row_limit-de72dfa33a3154e1.yaml

Override max_row_limit

---

doc/maas-checks/source/maas_checks_plugin.py

The doc change merged before I had a chance to push a small change with some cleanups that should have been done. One clarification to a TODO, a small renaming, and removing some commented out output.

Minor cleanups left out of 32f8feb

---

playbooks/maas-hummingbird.yml
playbooks/templates/rax-maas/lb_api_check_hummingbird_access.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_hummingbird_access.yaml.j2

These changes are required to support https://github.com/rcbops/rpc-hummingbird/pull/31

HUM-927 Work needed to enable transaction monitoring

---

playbooks/files/rax-maas/plugins/maas_common.py
playbooks/files/rax-maas/plugins/managed_k8s_services_local_check.py
playbooks/files/rax-maas/plugins/octavia_check_quota_limits.py
playbooks/maas-managed-k8.yml
playbooks/maas-openstack-octavia.yml
playbooks/site-osp.yml
playbooks/templates/common/macros.jinja
playbooks/templates/rax-maas/lb_api_check_octavia.yaml.j2
playbooks/templates/rax-maas/lb_ui_check_k8s.yaml.j2
playbooks/templates/rax-maas/run_plugin_in_venv.sh.j2
playbooks/vars/maas-openstack.yml
playbooks/vars/maas-osp.yml
releasenotes/notes/rpc-r-for-octavia-etg-9066e26ad9d692a9.yaml

This refactors our two maas playbooks two work with
both RPC-R and RPC-O.
RPC-R support is pretty barebone

K8S-1121 Octavia + ETS MaaS for RPC-R

---

playbooks/maas-openstack-designate.yml
playbooks/maas-openstack-octavia.yml
playbooks/site-osp.yml
playbooks/templates/rax-maas/designate_api_local_check.yaml.j2
playbooks/templates/rax-maas/designate_mdns_local_check.yaml.j2
playbooks/templates/rax-maas/lb_api_check_designate.yaml.j2
playbooks/templates/rax-maas/octavia_api_local_check.yaml.j2
playbooks/templates/rax-maas/octavia_lb_in_error_check.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_designate.yaml.j2
playbooks/vars/maas-osp.yml
releasenotes/notes/designate_for_osp-30ff78db4229730f.yaml

Refactors Designate checks to work with RPC-R

K8S-1361 rpc-maas doesn't install designate tests on RPC-R

---

playbooks/files/rax-maas/tools/rally_diag.sh

Change query for ports to work more better and dress up all the queries.

Updated rally_diag.sh

---

gating/static_analysis/checkmarx-pipeline

Add daily checkmarx scan

---

tests/test-ansible-functional.sh

Since https://review.openstack.org/#/c/620991 is merged

Remove temporary ansible runtime hack.

---

playbooks/maas-agent-install.yml
playbooks/maas-container-conntrack.yml
playbooks/maas-container-storage.yml
playbooks/maas-host-network.yml
playbooks/maas-hummingbird.yml
playbooks/maas-infra-memcached.yml
playbooks/maas-openstack-cinder.yml
playbooks/maas-openstack-designate.yml
playbooks/maas-openstack-glance.yml
playbooks/maas-openstack-heat.yml
playbooks/maas-openstack-ironic.yml
playbooks/maas-openstack-keystone.yml
playbooks/maas-openstack-magnum.yml
playbooks/maas-openstack-neutron.yml
playbooks/maas-openstack-nova.yml
playbooks/maas-openstack-octavia.yml
playbooks/maas-openstack-rally.yml
playbooks/maas-openstack-swift.yml
playbooks/maas-tigkstack-grafana.yml
playbooks/maas-tigkstack-telegraf.yml
playbooks/maas-verify.yml
playbooks/site-osp.yml

Removes string concatenation of pip packages

Fix pip lists in newer ansible versions

---

playbooks/common-tasks/maas_get_maasrc.yml
playbooks/common-tasks/maas_get_openrc.yml
playbooks/maas-managed-k8.yml
playbooks/maas-openstack-designate.yml
playbooks/maas-openstack-octavia.yml
playbooks/templates/rax-maas/lb_api_check_designate.yaml.j2
playbooks/templates/rax-maas/lb_api_check_octavia.yaml.j2
playbooks/templates/rax-maas/lb_ui_check_k8s.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_designate.yaml.j2
playbooks/vars/maas-osp.yml
tests/test-ansible-functional.sh

Update checks to work better, and faster, in both rpco and rpcr.

Fetch push

---

inventory/rpcr_dynamic_inventory.py
inventory/rpcr_tripleo_host_group_mapping.py
playbooks/common-tasks/maas_get_openrc.yml
playbooks/maas-pre-flight.yml
playbooks/vars/maas-osp.yml
playbooks/vars/main.yml
tests/env-prep.sh
tests/test-ansible-functional-osp-mnaio.sh

A few variable and file passing mechanism change to fix OSP gate
Signed-off-by: tonytan4ever <tony.tan@rackspace.com>

Fixing OSP gates

---

gating/check/run
playbooks/common-tasks/maas-agent-redhat-install.yml
playbooks/common-tasks/maas-agent-ubuntu-install.yml
playbooks/common-tasks/maas_get_maasrc.yml
playbooks/common-tasks/maas_get_openrc.yml
playbooks/files/rax-maas/plugins/ceph_monitoring.py
playbooks/files/rax-maas/plugins/maas_common.py
playbooks/library/gather_disk_device_facts
playbooks/maas-pre-flight.yml
playbooks/maas-verify.yml
playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2
playbooks/vars/maas-redhat.yml
playbooks/vars/maas-ubuntu.yml
tests/aio-create.sh
tests/env-prep.sh
tests/test-ansible-functional.sh
tests/test-setup.yml
tests/user_ceph_vars.yml

This change will deploy a functional rpc-ceph aio used for rpc-maas
testing.

Deploy rpc-ceph in rpc-maas tests

---

tests/aio-create.sh

The linux-image-extra package was renamed to linux-modules-extra in 3.13
and 4.4 kernel versions. This change updates the package in the bootstrap
role after checking out the EOL releases of upstream openstack.

Update missing linux-extra-image package

---

playbooks/files/rax-maas/plugins/horizon_check.py
playbooks/files/rax-maas/plugins/nova_cloud_stats.py
playbooks/maas-openstack-cinder.yml
playbooks/templates/rax-maas/cinder_volume_check.yaml.j2

These changes provide continued functionality of maas with the recent
consumption and architectural decisions around RPCO deployments.

Minor tweaks for internal rearchitecture

---

playbooks/library/service_discovery.py

This change provides a second pass option for CDC environments where no
private endpoints were detected during first pass. This will allow use
of public IPs with private network monitoring for these environments.

Add second pass logic for SDK service discovery

---

.gitignore
playbooks/library/service_discovery.py
playbooks/maas-openstack-cinder.yml
playbooks/maas-pre-flight.yml
playbooks/maas-sdk-integration.yml
playbooks/templates/rax-maas/cinder_volume_check.yaml.j2

This change generates additional facts relating to cinder backend pools
and unifies the methodology for which shared and local pools are
deployed.

Discover block storage hosts for backend pools

---

playbooks/files/rax-maas/plugins/holland_local_check.py

This fix add support for baremetal hosts to
execute the holland backup check

Fix holland plugin for baremetal hosts

---

playbooks/files/rax-maas/plugins/holland_local_check.py
tests/aio-create.sh
tests/env-prep.sh
tox.ini

- Reverting holland check changes breaking bare metal hosts and general container check
- Clamp tests to last Python 2 branches/hash

Minor fixes

---

gating/check/run
playbooks/common-tasks/maas-venv-create.yml
playbooks/vars/maas-openstack.yml
playbooks/vars/maas.yml
tests/aio-create.sh
tests/test-ansible-functional.sh

It has been a while since gating has been ran on rpc-maas.
These changes were required to get queens and train osa
aio tests working. I'm also testing out the github actions
workflow with this PR, so both tests should pass before a
merge.

JIRA: RPCOS-33 Working out gating/maas bugs.

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

The ceph health output provides a 'checks' dictionary for when the cluster
status is something other than 'HEALTH_OK'. Before we can start setting
up checks and alerts for these, we need them converted into metrics for
the rackspace monitoring agent.
These changes create a different 'health_checks' subcommand that will
default to 'HEALTH_OK(2)' for each and change it to the status value
in the 'checks' dictionary if found. I had to break these into sections
as each check can have a max of 50 metrics.  The '--section' argument
allows for mon,mgr,osds,device_health,data_health or misc. These line
up with the sections given in the following ceph document:
https://docs.ceph.com/docs/master/rados/operations/health-checks/
I also fixed a couple pep8 spacing issues in the process.

JIRA RPCOS-44 Add metrics for health checks

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

Bug fix to pull proper severity from the ceph health checks list.

JIRA RPCOS-44 Fixing severity status pull

---

INSTALL.md
playbooks/common-tasks/maas-venv-create.yml
playbooks/files/rax-maas/plugins/openmanage.py

- Fix install doc to use correct DDI for the maas_api_url
- Fix openmanage.py for python3

Minor OSP16 fixes

---

playbooks/files/rax-maas/plugins/hp_monitoring.py

HP MCP version 12.x is required for Ubtuntu 20.04.
This version removed the `hp-health` package in favor of iLO monitoring.
As hpasmcli is no longer accessible, the Memory, Processor and PowerSupplies
checks are reporting errors until ilo checks are used.

Add ilo4 checks for HP Gen9 to support Ubuntu 20.04

---

playbooks/maas-openstack-glance.yml

RPCOS-91 #time 2h Total work logged

Remove glance-registry check on newer releases

---

playbooks/maas-openstack-nova.yml

- nova console auth is no longer deployed with newer OpenStack releases
RPCOS-91 #time 30m Total work logged

Remove deprecated nova checks on newer releases

---

playbooks/files/rax-maas/plugins/README.md
playbooks/files/rax-maas/plugins/barbican_api_local_check.py
playbooks/maas-openstack-all.yml
playbooks/maas-openstack-barbican.yml
playbooks/templates/rax-maas/barbican_api_local_check.yaml.j2
playbooks/templates/rax-maas/lb_api_check_barbican.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_barbican.yaml.j2
playbooks/vars/main.yml

Adding initial barbican API check

---

playbooks/files/rax-maas/plugins/container_storage_check.py

The previous method of using chroot to check container storage fails
when the container uses a symlink from /etc/mtab to ../proc/self/mounts
since the container is running in an isolated pid/mnt namespace and
/proc/self is not visible in the chroot.
This commit uses the the `attach_wait` method from the `lxc` module to
run the df command in the container pid/mnt namespace and parses the
df output to gather usage percentage for each mounted device.
Fixes #724

Make storage check use df in container namespace
