README.md
cinder_api_local_check.py
galera_check.py
glance_api_local_check.py
horizon_check.py
keystone_api_local_check.py
memcached_status.py
neutron_api_local_check.py
nova_api_local_check.py
rabbitmq_status.py

Where a metric is a numerical (non boolean) value, we add a descriptive
unit to be displayed with the metric
Also ensure that all metrics include the name of the service/plugin from
which they are generated.
Finally, ensure that all boolean status metrics include 'status' in
their name
closes: #142
(cherry picked from commit b05d0d1b98171c5594cde735d4921b86bb86d35d)
Conflicts:
README.md

add units to all numerical metrics

---

cinder_api_local_check.py
cinder_service_check.py
disk_utilisation.py
elasticsearch.py
galera_check.py
glance_api_local_check.py
glance_registry_local_check.py
heat_api_local_check.py
horizon_check.py
keystone_api_local_check.py
maas_common.py
memcached_status.py
neutron_api_local_check.py
neutron_service_check.py
nova_api_local_check.py
nova_api_metadata_local_check.py
nova_service_check.py
openmanage.py
rabbitmq_status.py
service_api_local_check.py
swift-dispersion.py
swift-recon.py

maas has some particular requirements regarding the output. This
commit attempts to address the following:
- Report an error if the script attempts to return more than 30 metrics.
While the agent does log this and does stop sending metrics the status
of the check remains available. This could cause issues if the metrics
aren't used with alarms
- Uncaught exceptions generate a status message.
Exceptions don't generate a status message unless one is explicitly
set. Sometimes an exception may only occur if run by the agent. Status
messages have a limit of 256 characters so the text is taken from the
tail of the traceback.
- Log unhandled exceptions
The agent does a poor job of tracking plugin failures. This commit will
log unhandled exceptions to make debugging issues easier.
- Strip …

Increase control on data printed

---

maas_common.py
swift-recon.py

Instead of returning an empty dictionary, let's raise an exception
of our own which will document (in part) why we're failing here.

Raise an exception on invalid replication data

---

cinder_service_check.py
neutron_service_check.py
nova_service_check.py

Removes the positional argument validation as IPv4 address and updates
help messages.
Fixes #157
(cherry picked from commit 557b0d6a825b96820983cf86cf572cd0bc449866)

Accept DNS hostname or IP address as API host target

---

swift-recon.py

This update fixes the call to a non-existent method in maas_common
(status_error).
It does not look like this needs to be back-ported to juno
Fixes #170

Fix swift-recon.py

---

README.md
hp_monitoring.py

The hp_monitoring.py script adds basic hardware monitoring for HP boxes
and is designed to complement the openmanage.py script for Dell
hardware.
The script makes use of the utilities hpasmcli and hpssacli. Details of
the repo from which to get them can be found at
https://downloads.linux.hp.com/SDR/project/mcp/. The packages installed
were hp-health and hpssacli.

Add hp_monitoring.py script

---

README.md
conntrack_count.py

This commit adds a plugin to allow the number of connections and the
maximum number allowed to be monitored.
Issue: https://github.com/rcbops/rpc-maas/issues/163
(cherry picked from commit 7724f307be9ec4503c931406af79f7ba9684e9c3)
(cherry picked from commit ce6c10e14685755eba2969701aabc55bd3f94694)
(cherry picked from commit a0865f1c355874591a8f1769be1b3fe0e102c66c)
(cherry picked from commit d62594bcbba68b0dce62dbb409773a80aa210606)
(cherry picked from commit b317187719258dff3533e69debc200b9353dac70)
(cherry picked from commit 9bdf8137f9f4b917ffb8711d1ecfd5e2b3afc775)

Add conntrack_count.py

---

nova_api_local_check.py
nova_service_check.py

Currently, these scripts use v3 API however upstream os-a-d project no
longer enables v3 API.  This change uses v2.1 API instead, which
requires including tenant_id in the URL.
Closes issue #197

Update nova plugins to use v2.1 API

---

disk_utilisation.py

Fix for https://github.com/rcbops/rpc-maas/issues/177 disk_utilisation.py is not excluding nb block devices and bails out on 30 metric limit

Fix for issue 177.

---

nova_api_local_check.py
nova_service_check.py

In commit 347463d we changed the nova plugins to use v2.1 instead of
v3.  This was done as v3 is now deprecated and defaults to being
disabled in os-ansible-deployment.  The problem was the testing was
done on a deployment w/ v3 enabled and it appears there is some
coupling between v2.1 and v3.
This commit simply updates the nova plugins to use v2 instead of v2.1.
Thanks to @miguelgrinberg for spotting this!
Closes issue #197

Use nova API v2 instead of v2.1

---

horizon_check.py

requests.packages.urllib3.disable_warnings is only available on requests
2.4.0 or later. Right now, we package have a lower limit on 2.2.0 and
all versions before 2.4.0 will cause an AttributeError when calling
this.
/cc @stevelle

Disable warnings conditionally

---

rabbitmq_status.py

This PR backports the following two changes from master to juno:
b5742ac Update rabbitmq_status.py
b11058d Create rabbitmq_max_channels_per_conn metric
Closes issue #188

Backport rabbitmq_status.py changes to juno

---

cinder_service_check.py

The script cinder_service_check.py defines an optional host parameter
that is designed to filter the results, returned by the cinder API, so
that only services on the specified host are returned. The MaaS setup
role, that configures the checks that use this script, uses '--host'.
The script does not use the host argument if supplied.
This patch fixes the script so that the results returned are filtered
by host, where host includes any backends/pools on that host.
Closes-bug: #216

cinder_service_check.py not using --host option

---

hp_monitoring.py

The current HP hardware monitors only cover cpu/dimm/disk. This commit
adds status monitoring via hpssacli for controller/cache/battery status
too
Fixes: #218

add hp monitors for disk controller/cache/battery

---

neutron_metadata_local_check.py

The neutron metadata agent proxy provides access from within neutron
network namespaces to the neutron metadata agent and thus to the
various sources of metadata provided to instances on 169.254.169.254
at port 80 when cloud-init is used.
The metadata agent has monitoring in RPC but has been reported to be
running but non-responsive on some occasions (see issue #342). The
new check tests the agent's proxy from within the namespace to
monitor responsiveness. Because the agent will use the client host
IP to look for metadata but the request is not originating from an
instance a 404 Not Found response is expected from the agent.
Because local checks are expected to operate from the host rather
than inside a container, and the host does not have ready access to
neutron network namespaces, the …

Add maas external check for neutron metadata proxy

---

rabbitmq_status.py

There is currently a print statement in the rabbitmq_status.py script
that prints out a line starting with 'status err '. This is a special
type of status line that causes a metric called legacy_state to be
created. This metric should not be created. The status_err function
should be used instead of using print directly.
This commit updates the line to use status_err. This will prevent the
metric legacy_state from being created. It will also cause the script
to exit with a return code of 1.

Fix status error output

---

README.md
ceph_monitoring.py
cinder_api_local_check.py
cinder_service_check.py
conntrack_count.py
disk_utilisation.py
elasticsearch.py
galera_check.py
glance_api_local_check.py
glance_registry_local_check.py
heat_api_local_check.py
horizon_check.py
hp_monitoring.py
keystone_api_local_check.py
maas_common.py
memcached_status.py
neutron_api_local_check.py
neutron_metadata_local_check.py
neutron_service_check.py
nova_api_local_check.py
nova_api_metadata_local_check.py
nova_service_check.py
openmanage.py
rabbitmq_status.py
service_api_local_check.py
swift-dispersion.py
swift-recon.py

We have a requirement to move the plugins back out to rpc-maas, in
order that other groups can consume (and contribute to) the plugins
more easily.
This commit synchronises the plugins here with those that exist inside
rpc-openstack at this time.
Note - there is a funky way of preserving all history of commits to
these files when they were in rpc-openstack (using git filter-branch).
Sadly, there is very little history to preserve since we lost it in
the commit which moved all plugins to the plugins directory (7a3cd17)
because 'git mv' was not used from what I can tell. This means that I
can't cleanly apply that history here, and so a big commit including
all the changes is the only way to go. Sorry.

synchronize kilo branch with all plugins in rpc-openstack

---

rabbitmq_status.py

Check the JSON response body for valid data when requesting channels.
After discussions with @git-harry and thinking the error over again, I've
decided that it is not technically an error to not have channels configured.
It is an error to receive an empty response when checking the overview and
nodes API endpoints. I will fix those in a later bug report.
Closes-Bug: #442

Check json_resp before using max()

---

README.md
galera_check.py

_NOTE: this is a partial cherry-pick (essentially without the template bits, and only the plugin bits) of the following (already merged) commit from master:_
_https://github.com/rcbops/rpc-openstack/commit/5b24196daa6112f711912bea928542f9ae0a23c9_
---
add some connection related metrics to galera_check plugin
Up to now, we've been grabbing specific matching data from the output
of 'SHOW STATUS'. This commit adds the output from 'SHOW VARIABLES', so
that we can grab the configuration vars too. Additionally, we no longer
limit the captured data from 'SHOW STATUS'.
Having all of the output from 'SHOW VARIABLES' and 'SHOW STATUS' will
make it easy to add any further metrics/alarms to this plugin in the
future.
Additionally, 'SHOW STATUS' was changed to 'SHOW GLOBAL STATUS' to
ensure we are …

Add some connection related metrics to galera_check plugin

---

README.md
rabbitmq_status.py

* Adds metrics:
* notification_messages
* msgs_excl_notifications
* Refactors the rabbitmq plugin to reduce duplicated code
Related: #633
Trello: https://trello.com/c/widYAV5F/35-add-new-monitor-rabbitmq-queue-length

Add queue length monitoring to rabbitmq plugin

---

README.md

This repo is no longer maintained. The code it manages has been moved to
https://github.com/rcbops/rpc-openstack. This commit updates the readme
to make clear the repo's current status.

Update readme to explain current status

---

defaults/main.yml

This fix adheres to the OSA contraints on psutil and
python-novaclient to allow rpc_maas to run in Ocata.
Connects rcbops/u-suk-dev#1642

Fix dependencies in MaaS for Ocata

---

defaults/main.yml

RPC-Openstack sets ssl_check to false in user variables and this
was never tested in gating with a different variable.
Let's adapt the default, and if needed later, increase test
coverage by adding a scenario to test this.

Set the vars to proper defaults

---

defaults/main.yml

It appears that this original change causes the process checks to fail due to the psutil version that 
we changed it to. 
`` line 137, in <module>\\n    main(args)\\n  File \"/usr/lib/rackspace-monitoring-agent/plugins/process_check_container.py\", line 127, in main\\n    proces
s_names=args.processes)\\n  File \"/usr/lib/rackspace-monitoring-agent/plugins/process_check_container.py\", line 88, in check_process_running\\n    procs = get_processes(parent_pid=init_pid)\\n  File \"/usr/lib/rackspace-monitoring-agent/plugins/process_check_container.py\", line 64, in get_processes\\n    procs = [x for x in psutil.Process(parent_pid).get
_children()]\\nAttributeError: \\'Process\\' object has no attribute \\'get_children\\'\\n') ``
Also, nova has similar issues.
Reverts rcbops/rpc-maas#236

Revert "Fix dependencies in MaaS for Ocata"

---

tasks/maas_host_install.yml

This patch adds the ability to use a different apt
repository for the maas packages using an alternative
key set and URL configuration. This is to facilitate
the ability to artifact the MaaS apt repo and
configure RPC-O to use the artifacted repo instead of
the upstream source.
Retries are added to the apt key addition to improve
reliability and the conditional for the repo/key
additions are removed as the values are defaulted
and are therefore always defined.
Connects https://github.com/rcbops/u-suk-dev/issues/1657

Provide more flexible and reliable apt repo config

---

files/plugins/swift-recon.py
tests/ansible-role-requirements.yml
tests/host_vars/hap1.yaml
tests/host_vars/infra1.yml
tests/host_vars/infra2.yml
tests/host_vars/infra3.yml
tests/host_vars/localhost.yml
tests/host_vars/swift1.yml
tests/inventory
tests/rpc-maas-overrides.yml
tests/test-install-haproxy.yml
tests/test.yml

This change allows the testing infra to begin verifying the checks deployed. To do this we need to have haproxy running because maas has a hard dependency on load balancer based monitoring at the moment.

Add additional functional testing with haproxy

---

defaults/main.yml
tasks/maas_infra.yml
tests/rpc-maas-overrides.yml

This variables is used in various places throughout the role.
Moving it to defaults/main.yml ensures it's available to all
tasks.
This also solves the problem of some tasks not having scope to this variable.
Without this change, the following errors occur:
https://gist.github.com/anonymous/98d41a5bc0b0aaae6299c1b203c0b412

Move internal_vip_address to defaults/main.yml

---

tasks/maas_infra.yml

Using 'in' causes scenarios where the inventory_hostname substring
is "in" the groups['rabbitmq_all'][0] string, particularly when
processing the physical hosts. This, in turn, causes the physical
host to be unintentionally targeted.
Connects https://github.com/rcbops/rpc-openstack/issues/2253

Replace 'in' with '==' when host filtering

---

vars/main.yml

This commit filters out QEMU DVD-ROM devices from the
disk_util_devices list, in turn removing them from
being included in alarm criteria for the disk_utilisation
plugin.
Connects https://github.com/rcbops/rpc-openstack/issues/2255

Filter out QEMU DVD-ROM from disk_util_devices

---

files/plugins/neutron_service_check.py
releasenotes/notes/neutron-service-check-uses-fqdn-d861768de0f95f92.yaml
templates/neutron_dhcp_agent_check.yaml.j2
templates/neutron_l3_agent_check.yaml.j2
templates/neutron_linuxbridge_agent_check.yaml.j2
templates/neutron_metadata_agent_check.yaml.j2

This change modifies the neutron_service_check.py plugin to
utilize the FQDN as an argument for checking neutron services.
It was previously only using the hostname.
Connects rcbops/rpc-openstack#1603

Allow the use of FQDNs in neutron_service_check.py

---

defaults/main.yml
files/plugins/rabbitmq_status.py
templates/rabbitmq_status.yaml.j2

Adds metrics to rpc maas plugin for consumers. Provides total
consumer count, as well as consumer count for each vhost.
connects rcbops/u-suk-dev#855

Adds consumers metrics to maas plugin

---

files/plugins/rabbitmq_status.py

This commit fixes a `ValueError: max() arg is an empty sequence` error
encountered in some environments.  This error is triggered when the plugin
runs while there are no connections reported by RabbitMQ, which is an expected
scenario in a swift-only or keystone-only environment.
The change effectively adds a '0' default to max()'s arguments.
Connects: #253

Fix RabbitMQ status plugin for swift-only control planes

---

files/plugins/hp_monitoring.py

This fix add a try catch for a given HP utility command
and returns false if the output did not match expectations.
This also solves issues where output is omitted,
for example the RAID battery issue, leading to BadOutputError.
Closing-Bug: rcbops/u-suk-dev#1241

Adding try-catch for HP commands

---

files/plugins/rabbitmq_status.py

The default for max_chans should be a bare '0' value, not a single-item list.
Prior to this commit, the plugin returns the '0' in a list, which the MaaS
agent won't parse.
Closes: #253

Fix default value for for max_chans metric

---

playbooks/maas-openstack-swift.yml
playbooks/vars/main.yml

When installing the swift checks the swift client is needed. Prior to
this commit the tasks depended on OSA and the OSA release to upload
objects into swift to create the needed checks. This change removes
the artificial OSA dependency in favor of using the client versions
installed into the maas-venv.

Remove OSA dependency

---

doc/source/index.rst
playbooks/maas-infra-filebeat.yml
playbooks/maas-restart.yml
playbooks/site.yml

This change implements optional flow control for restarting the RAX-MaaS
agent. This is needed due to limitations in the rax-maas-agent causing
issues when multiple restarts are issued within the same minute.

Add restart flow clontrol

---

playbooks/files/plugins/swift-recon.py

Fix bug in swift-recon plugin to remove quotes from the `openstack_version` variable. Allow's Kilo to function as there are no virtual environments.

Remove quotes in openstack_version variable

---

playbooks/templates/plugins/rabbitmq_status.py
playbooks/templates/rabbitmq_status.yaml.j2

Queues having no consumers subscribed and don't
contain any messages are excluded from the
consumer check.
This is done to reduce alerts on non critical conditions.

Excluding empty queues from consumer check

---

playbooks/handlers/main.yml
playbooks/maas-agent-install.yml
playbooks/maas-agent-setup.yml
playbooks/maas-ceph-mon.yml
playbooks/maas-ceph-osd.yml
playbooks/maas-container-storage.yml
playbooks/maas-host-cdm.yml
playbooks/maas-host-kernel.yml
playbooks/maas-host-network.yml
playbooks/maas-host-vendor.yml
playbooks/maas-infra-elasticsearch.yml
playbooks/maas-infra-filebeat.yml
playbooks/maas-infra-galera.yml
playbooks/maas-infra-lb-ssl.yml
playbooks/maas-infra-memcached.yml
playbooks/maas-infra-rabbitmq.yml
playbooks/maas-infra-rsyslogd.yml
playbooks/maas-openstack-cinder.yml
playbooks/maas-openstack-glance.yml
playbooks/maas-openstack-heat.yml
playbooks/maas-openstack-horizon.yml
playbooks/maas-openstack-keystone.yml
playbooks/maas-openstack-magnum.yml
playbooks/maas-openstack-neutron.yml
playbooks/maas-openstack-nova.yml
playbooks/maas-openstack-swift.yml

Added step to detect and limit container storage checks to only contianer
hosts. This ensures we're not attempting to deploy container checks on
non-container hosts.

Detect container hosts

---

playbooks/files/maas_telegraf_format.py
playbooks/files/plugins/container_storage_check.py
playbooks/templates/run_plugin_in_venv.sh.j2
playbooks/vars/maas-openstack.yml

Running all plugins from MaaS in a single pass is slow, this chnage
implements threading allowing the collection of the plugins to happen
much faster.
Three bugs were discovered:
* Should a container be stopped the pid returned for the container is
"-1" which will fail a lookup, a change has been added to condition has
been added to check for a negative pid and skip when needed.
* The horizon dashboard variable had a space in it causing the lookup
to fail. This removes the extra bits and corrects the plugin
failure.
* The venv wrapper used to source the virtual env and then run the a
python utility while this mostly works it breaks a shell environment
should the check fail to run. Calling the virtual environment python
directly resolves this issue.
Signed-off-by: Kevin Carter …

Thread the telegraf entrypoint

---

playbooks/files/tools/rpc-maas-tool.py

When verifying maas there's no need to check a plugin if it's been
disbaled. This patch makes it so the maas verification tool skips checks
that are disbaled.

Convert verify maas py tool to skip disabled

---

doc/source/usage.rst
playbooks/files/maas_telegraf_format.py
playbooks/files/plugins/container_storage_check.py
playbooks/files/plugins/maas_common.py
playbooks/files/plugins/process_check_container.py
playbooks/files/tigkstack/deploy_go.sh
playbooks/files/tigkstack/deploy_influxdbrelay.sh
playbooks/maas-tigkstack-all.yml
playbooks/maas-tigkstack-influxdb.yml
playbooks/maas-tigkstack-telegraf.yml
playbooks/templates/tigkstack/grafana.ini.j2
playbooks/templates/tigkstack/influxdb.conf.j2
playbooks/templates/tigkstack/influxdbrelay.conf.j2
playbooks/templates/tigkstack/influxdbrelay.service.j2
playbooks/templates/tigkstack/relay.toml.j2
playbooks/templates/tigkstack/telegraf.conf.j2
playbooks/vars/maas-tigkstack.yml
playbooks/vars/main.yml
tests/inventory
tests/rpc-maas-overrides.yml
tests/test.yml

Two new playbooks have been added to deploy telegraf and influxdb into
an environmeent and begin collecting metrics locally using the same
plugins powering the rax-maas check system.
In the course of adding this collection capability I discovered the
plugin `process_check_container.py` was throwing an error should a given
container lookup fail. To correct this I've added an exception handler.

Added telegraf and influx metric collection

---

playbooks/templates/rax-maas/plugins/rabbitmq_status.py

The notifications queues can only be execluded from monitoring
if one or more consumer is present on the queue.
If the queues are excluded from monitoring but no consumer is present,
it will lead to instabilities of RabbitMQ, ultimately stopping
operations due to system limitations (memory/disk).
The notification_driver need to be properly set to noop if the
messages generation for the notification queues should be suppressed.
Additionally the new versioned_notifications queue is included in this
check.
Closes-Bug: #286

Exclude notifications queues under condition

---

playbooks/files/rax-maas/plugins/hp_monitoring.py

For customers that use SSD in their arrays, the cache is not enabled and will have a status of 'Not Configured'. This inclusion should still catch failures of the cache as they will show up as disabled.

Allow cache status to remain 'Not Configured' when ssds are utilized

---

doc/source/static-inventory.rst
doc/source/usage.rst
playbooks/maas-tigkstack-influxdb.yml
playbooks/templates/tigkstack/relay.toml.j2
playbooks/templates/tigkstack/telegraf.conf.j2
tests/test-ansible-functional.sh

This change creates a specific group for influxdb deployments. This
change is being done so that we dont assume the log hosts will be used
for metric collection.

[LA-314] change log_hosts to influx_hosts

---

playbooks/vars/maas-openstack.yml

Currently, deploying rpc-maas on a multi-node deplay fails when
attempting to upload a file with the swift client as this role
currently does not install python-swiftclient.
This commit simply adds python-swiftclient to the
maas_openstack_swift_pip_packages variable.

UG-634 Install python-swiftclient on swift hosts

---

playbooks/maas-tigkstack-influxdb.yml

no_log: True to remove passwords from appearing in the logs.
no_log was introduced in ansible 1.8 and should be easy to
backport.

Do not leak password in ansible log

---

playbooks/library/raxmon.py
playbooks/templates/rax-maas/raxrc.j2
playbooks/vars/maas-openstack.yml
playbooks/vars/main.yml

The hardcoded nature of raxmon SSL verification can be problematic if a customer is using a non-transparent web proxy, which will fail verification checks. This allows an override for verification allowing the playbooks to properly set an entities agentID.

Override raxmon ssl verification for non-transparent web proxy

---

playbooks/maas-verify.yml
playbooks/vars/maas-verify.yml
test-requirements.txt

Deploying rpc-maas on a multi-node fails on the verification stage,
because we're not explicitly installing the futures module on all
hosts.  It appears to be getting pulled in implicitly on some hosts
via other modules and therefore isn't failing across the board.
This commit simply creates a new vars file for the verification stage,
and updates maas-verify.yml to install this new pip package set.
Lastly, we remove futures from test-requirements.txt since it is now
installed via the maas-verify.yml playbook.

UG-634 Add vars file for verification dependencies

---

playbooks/files/pip-constraints.txt
playbooks/maas-tigkstack-telegraf.yml
playbooks/vars/maas-tigkstack.yml

The script `maas_telegraf_format.py` requires `PyYAML` to be installed.
On an AIO this dependency is met because the AIO host is also the
deployment node. When there are multiple hosts, such as a multi-node
AIO, `PyYAML` is missing.
This commit installs `PyYAML` into the `maas_venv` and uses the Python
binary in that virtual env to run the script.

LA-367 Install maas_telegraf_format.py dependency

---

playbooks/maas-tigkstack-telegraf.yml

The package `virtualenv` needs installing prior to deploying
`maas_telegraf_format.py`. In general, due to the ordering of MaaS
playbooks in rpc-openstack, it is already installed. However, currently
rpc-gating configures MaaS separately and so `virtualenv` is not
installed when `maas-tigkstack-telegraf.yml` runs.
In addition, two `delegate_to` lines are removed given that the play is
already targeting the group `hosts`.

LA-367 Install virtualenv prior to telegraf

---

doc/source/usage.rst
playbooks/files/rax-maas/plugins/ceph_monitoring.py
playbooks/maas-ceph-mon.yml
playbooks/maas-ceph-osd.yml
playbooks/templates/rax-maas/ceph_cluster_stats.yaml.j2
playbooks/templates/rax-maas/ceph_mon_stats.yaml.j2
playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2
playbooks/vars/main.yml

The legacy rpc-o ceph installations used a non-standard (ceph-ansible)
installation process which put both OSDs and MONs in lxc containers.
This means that maas needs to execute all of the ceph monitoring
commands from within these containers in order to retrieve metrics. This
change implements a container-name flag which supports a single argument
within all of the ceph checks allowing us to monitor these legacy
environments. To enable this capability the option,
`maas_rpc_legacy_ceph1` needs to be set "true".

Add the ability to monitor legacy rpc-o ceph installs

---

playbooks/vars/maas-ubuntu.yml

The Python package lxml requires libxml2 and libxslt to be installed.

LA-371 Install required apt packages for lxml

---

playbooks/templates/rax-maas/lb_api_check_horizon.yaml.j2

This commit adds a trailing slash to the Horizon URL.  Without this,
the check receives a 301 redirect and then fails.  After this change,
the check receives a 200 and passes.
Closes: #313

Add a trailing slash to Horizon URL

---

playbooks/templates/rax-maas/ceph_cluster_stats.yaml.j2
playbooks/templates/rax-maas/ceph_mon_stats.yaml.j2
playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2

The maas agent can't deal with unicode, this change ensures that no unicode is used with the args list.

fix unicode strings

---

playbooks/templates/rax-maas/rackspace-monitoring-agent.cfg.j2
playbooks/vars/main.yml

This commit adds a variable named `maas_proxy_url`, which exposes the
`monitoring_proxy_url` configuration item in Rackspace monitoring agent
configuration file.
Closes: #308

Add support for HTTP proxy with MaaS agent

---

playbooks/templates/rax-maas/lb_api_check_cinder.yaml.j2
playbooks/templates/rax-maas/lb_api_check_glance.yaml.j2
playbooks/templates/rax-maas/lb_api_check_heat_api.yaml.j2
playbooks/templates/rax-maas/lb_api_check_heat_cfn.yaml.j2
playbooks/templates/rax-maas/lb_api_check_heat_cloudwatch.yaml.j2
playbooks/templates/rax-maas/lb_api_check_horizon.yaml.j2
playbooks/templates/rax-maas/lb_api_check_keystone.yaml.j2
playbooks/templates/rax-maas/lb_api_check_neutron.yaml.j2
playbooks/templates/rax-maas/lb_api_check_nova.yaml.j2
playbooks/templates/rax-maas/lb_api_check_swift_access.yaml.j2
playbooks/templates/rax-maas/lb_api_check_swift_healthcheck.yaml.j2
playbooks/vars/main.yml

This commit splits the `maas_external_ip_address` variable so that
different values can be configured in MaaS's `target_hostname` and
`url` settings.  This is required for environments where OpenStack
endpoints are not resolvable by the MaaS pollers, which requires
setting an IP for `target_hostname` and the internally resolvable
hostname in the `url`.
Closes: #311

Add maas_external_hostname variable

---

playbooks/templates/tigkstack/telegraf.conf.j2

If we define multiple inputs, instead of multiple commands, the
inputs will be handled separately, instead of having a spike
of all the commands to run.
This lightens the load and allow more aggressive data collection
without ooming on low end machines.

Allow telegraph to schedule the inputs

---

playbooks/files/rax-maas/plugins/swift-recon.py
playbooks/templates/rax-maas/swift_account_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_async_check.yaml.j2
playbooks/templates/rax-maas/swift_container_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_md5_check.yaml.j2
playbooks/templates/rax-maas/swift_object_replication_check.yaml.j2
playbooks/templates/rax-maas/swift_quarantine_check.yaml.j2
playbooks/templates/rax-maas/swift_time_sync_check.yaml.j2
playbooks/vars/maas-openstack.yml
tests/user_kilo_vars.yml

This change modifies the swift-recon MaaS plugin to allow the directory
containing swift-recon to be specified. This change removes the need for
the plugin to try to discover the version.
Checking `/etc/openstack-release` for the version to use in general
works however due to the ordering of playbooks in leapfrog upgrades this
causes the wrong version to be used. The use of this approach also
lengthens the time of plugin failure during an upgrade given the
separation between creating the release file and updating Swift.

LA-378 Fix swift-recon release identifier

---

playbooks/common-tasks/maas-agent-ubuntu-install.yml
playbooks/maas-tigkstack-grafana.yml
playbooks/maas-tigkstack-influxdb.yml
playbooks/maas-tigkstack-telegraf.yml
playbooks/vars/maas-tigkstack.yml
playbooks/vars/main.yml

In order to ensure that RPC-O deployments make use
of a frozen set of apt artifacts, the repo/key
settings must be overridable.
While it'd be ideal for the variables to be set as
role defaults, allowing these settings to be set
via group_vars - this is not possible due to the
way playbooks have been used instead of roles.
As such, we use vars and RPC-O will be forced to
use extra-vars as that's the only option which
has a higher precedence.

RE-312 Implement overridable vars for influx repo

---

tests/aio-create.sh

We don't need to build a galera or rabbit cluster, and we aren't testing
multiple Keystone/Horizon/Repo servers.
This patch changes the affinity to "1" for each of the services to avoid
multiple containers being built for the same service, and to avoid a big
in the EOL'd Liberty branch causing issues with mysql connections.
We can't use config overrides as there is a bug in liberty that means
integers cant be interpreted properly - so we have to sed the repo
directly.

Change affinity to 1 for MaaS Testing

---

playbooks/maas-restart.yml

Standalone ceph deploys are currently erroring out as rackspace-monitoring-poller won't be deployed there, but the restart task for the poller first checks for `groups['shared-infra_hosts']`.
That group doesn't exist in the stripped down inventory where this is being run, so flipping the ordering to first check for the poller's deployment will keep us from continuing on in the `when` checks for things like that group which might not be available.

Rearrange poller restart for standalone ceph

---

playbooks/maas-openstack-horizon.yml
playbooks/templates/rax-maas/lb_ssl_cert_expiry_check.yaml.j2

Fix missing monitoring_zones_poll which is failing validation preventing the check from deploying in the monitoring agent. Also replicate disabled status of the check across nodes and destination on disk.

Fix LB ssl expiry check

---

playbooks/files/rax-maas/plugins/maas_common.py

If a customer has both v2 and v3 endpoints, it's possible to incorrectly associate the wrong endpoint if it's iterated through first. This change simply verifies that the endpoint is the proper version before it's set.

Fix potential issue of associating an improper keystone endpoint

---

playbooks/templates/tigkstack/telegraf.conf.j2
playbooks/vars/maas-tigkstack.yml

`telegraf_plugin_ping_urls` represents a list of hosts to ping. This
plugin is only used if there is one or more URLs specified. This plugin
is added to allow instance monitoring during upgrade test builds.

LA-436 Enable use of telegraf ping plugin

---

playbooks/templates/rax-maas/galera_check.yaml.j2

The galera check template did not have properly terminated variables. They have now been updated to display their associated values.

Fix galera template variables

---

playbooks/templates/rax-maas/container_storage_checks.yaml.j2

The template is currently generated with an IP address, which can be a bit confusing for support when a ticket is generated. Updated the variable to `inventory_hostname` instead so that identification is easier.

Change alarm criteria variable ansible_host to inventory_hostname

---

playbooks/templates/rax-maas/network_throughput.yaml.j2
playbooks/vars/maas-host.yml

Attempt to utilize `ansible_default_ipv4.speed` (ansible 2.0+) to build the interface speed and default to 1Gb. This resolves the issue of it being defaulted to 0 within the template, preventing continual state changes in production.

Properly set interface speed instead of defaulting to 0

---

playbooks/templates/rax-maas/filesystem.yaml.j2

Template was improperly deploying as a result of not specifying the value of `item.filesystem`

Fix issue with filesystem template population

---

playbooks/files/rax-maas/plugins/holland_local_check.py
playbooks/maas-infra-galera.yml
playbooks/templates/rax-maas/holland_local_check.yaml.j2
playbooks/vars/maas-infra.yml
playbooks/vars/main.yml

Holland was only configured to deploy against newton with the new virtualenv configuration. This change enables the ability to determine if Holland should be deployed at all, and if a virtualenv should be used.

Fix issue preventing Holland from deploying on all supported rpc-o versions

---

playbooks/common-tasks/maas-poller-ubuntu-install.yml

When using the apt module you can pass a list, but not separated by
spaces, it should just be the list var. The current package install for
maas-poller will break, this patch fixes that and makes the maas-agent
packages install in the same, more efficient, way - that prevents the
need for a task per package.

Fix using a list for packages instead of with_items

---

playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2

For testing multiple OSD hosts in an AIO we need to run these in
containers, we need to target OSD MaaS against the container correctly,
this patch allows the container_name to be passed to ceph_monitoring.py.

HUM-304 Monitor Ceph OSD service in containers

---

tests/test-ansible-functional.sh

For non OpenStack deploys we shouldnt enforce the use of
openstack-ansible. For example, for deploying Ceph standalone.
We should allow MaaS to not force the use of openstack-ansible binary
and instead allow this to be set by an environment variable.

HUM-304 Allow the use of other ansible-playbook binaries

---

playbooks/vars/maas-ubuntu.yml

disk_utilisation.py requires sysstat for iostat to be present. In RPC-O
the openstack-hosts role will install sysstat so for RPC-O it was always
present.
When using a standlone ceph deployment or other service that doesn't
require the openstack-hosts role, we need sysstat in order to run the
disk_utilisation.py monitoring script.

HUM-304 Install sysstat for disk_utilisation.py

---

playbooks/maas-restart.yml

For ceph standalone integration, fewer tasks have run, and the MaaS
agent fails to restart for longer.
This patch adds additional retries and a slightly longer delay to ensure
the service restarts properly.

Increase maas-restart retries

---

playbooks/maas-verify.yml

RE provide environment variables which hold the path to the
correct place to store artifacts and test results:
* RE_HOOK_ARTIFACT_DIR
* RE_HOOK_RESULT_DIR
These are now available in the IRR jobs so can be used here.
Depends: https://github.com/rcbops/rpc-gating/pull/450

RE-613 Respect artifact location environment vars

---

playbooks/templates/rax-maas/rabbitmq_status.yaml.j2

Fix alarm label to align naming across all templates.

RO-2619: Change alarm label to be consistent with other alarms

---

playbooks/templates/rax-maas/hp-check.yaml.j2
playbooks/templates/rax-maas/ironic_api_local_check.yaml.j2
playbooks/templates/rax-maas/lb_api_check_ironic_api.yaml.j2
playbooks/templates/rax-maas/maas_poller_fd_count.yaml.j2
playbooks/templates/rax-maas/openmanage-memory.yaml.j2
playbooks/templates/rax-maas/openmanage-processors.yaml.j2
playbooks/templates/rax-maas/openmanage-vdisk.yaml.j2
playbooks/templates/rax-maas/private_ping_check.yaml.j2
playbooks/templates/rax-maas/private_ssh_check.yaml.j2

Some alarm definitions didn't include the override option for changing the notification plan. This ensures all templates have the ability to do so.

Update notification plans allowing everything to be overridden

---

playbooks/maas-openstack-swift.yml

The initial implementation assumed a single deployment node was used for both regions. It turns out multi-region swift in our implementation uses two deployment nodes, one per data center. This change allows us to define a single node per region/deployment host instead of the default two.

Allow limiting swift-recon checks to one proxy node per deployment

---

gating/generate_release_notes/generate_release_notes.sh
gating/generate_release_notes/generate_reno_report.sh
gating/generate_release_notes/release_notes_dockerfile
gating/generate_release_notes/run

This changes adds support for the rpc-gating generate_release_notes
hook.
New releases will now automatically have release notes generated from
those managed by Reno. If there are no Reno notes for the release that
will be explicitly stated in the release notes.
This code is ported from that used by rpc-openstack, with the use of
rpc-differ removed. The same basic structure is maintained to simplify
working on the two projects and to make it easier to unify if this ever
becomes something that is centrally managed.
Test with new note: https://github.com/wherenoworg/rpc-maas/releases/tag/987.654.3210
Test without new note: https://github.com/wherenoworg/rpc-maas/releases/tag/987.654.3211

RE-360 Include Reno notes in release notes

---

playbooks/maas-verify.yml

Previously there were no spaces between --excluded check arguments
which lead to a failure to parse the arguments correctly. This
commit corrects that.

RO-2832 Fix very-maas spacing

---

playbooks/maas-poller-setup.yml
playbooks/maas-restart.yml

Rackspace Monitoring developers have removed the `.systemd.service` naming convention in the stable release of the rackspace-monitoring-poller package. This change removes all instances of the original name allowing playbooks to deploy properly.

Update poller package to remove .systemd.service naming

---

gating/generate_release_notes/generate_release_notes.sh
gating/generate_release_notes/generate_reno_report.sh
gating/generate_release_notes/release_notes_dockerfile
gating/generate_release_notes/run

This changes adds support for the rpc-gating generate_release_notes
hook.
New releases will now automatically have release notes generated from
those managed by Reno. If there are no Reno notes for the release that
will be explicitly stated in the release notes.
This code is ported from that used by rpc-openstack, with the use of
rpc-differ removed. The same basic structure is maintained to simplify
working on the two projects and to make it easier to unify if this ever
becomes something that is centrally managed.
Issue: RE-831
(cherry picked from commit 8eae37a7203d25055ff558f8703ef1a5c91d2b9b)

RE-831 Include Reno notes in release notes

---

doc/utils/README.rst
doc/utils/maas_checks_util.py
doc/utils/requirements.txt

This module is to be used by a Sphinx extension in the privatecloud-docs repo to replace the tables that were manually generated for all of the checks and their alarms, as wanted by https://rpc-openstack.atlassian.net/browse/TURTLES-245

Expose check details, criteria, variables for automated documentation

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py
playbooks/files/rax-maas/plugins/cinder_service_check.py
playbooks/files/rax-maas/plugins/neutron_service_check.py
playbooks/files/rax-maas/plugins/nova_cloud_stats.py
playbooks/files/rax-maas/plugins/nova_service_check.py
playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2
playbooks/templates/rax-maas/cinder_backup_check.yaml.j2
playbooks/templates/rax-maas/cinder_scheduler_check.yaml.j2
playbooks/templates/rax-maas/cinder_volume_check.yaml.j2
playbooks/templates/rax-maas/neutron_dhcp_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_l3_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_linuxbridge_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_metadata_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_metering_agent_check.yaml.j2
playbooks/templates/rax-maas/nova_cert_check.yaml.j2
playbooks/templates/rax-maas/nova_cloud_stats_check.yaml.j2
playbooks/templates/rax-maas/nova_compute_check.yaml.j2
playbooks/templates/rax-maas/nova_conductor_check.yaml.j2
playbooks/templates/rax-maas/nova_consoleauth_check.yaml.j2
playbooks/templates/rax-maas/nova_scheduler_check.yaml.j2
playbooks/templates/rax-maas/plugins/rabbitmq_status.py
playbooks/templates/rax-maas/rabbitmq_status.yaml.j2
playbooks/vars/main.yml

Fixes hard-coded HTTP endpoints for the following checks:
- nova service checks
- nova cloud stats checks
- cinder service checks
- neutron service checks
- ceph radosgw checks
- rabbitmq checks
This also makes the nova cloud stats hit the VIP instead of the ansible
host so proper TLS termination can occur in that case.

Fix some hard-coded http endpoints

---

playbooks/maas-host-private-checks.yml

This playbook was missing the `maas_current_group` fact which caused the playbook to fail when running the handler.

Add fact to prevent handler failure

---

playbooks/templates/rax-maas/rackspace-monitoring-poller.cfg

The MaaS team is adding poller functionality similarly to the agent. Updating the template to include this value.

Add monitoring_proxy_url to poller configuration

---

playbooks/vars/maas-agent.yml
playbooks/vars/maas-verify.yml

This is required for rpc-maas-tool, which is used by maas-verify to
check that MaaS functioning correctly.

RE-1082 Ensure pyyaml is installed in MaaS venv

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py
playbooks/maas-ceph-raxmon.yml
playbooks/templates/rax-maas/ceph_mon_stats.yaml.j2

In order to support luminous, we need to allow access to client.raxmon
for the mgr service (which is required to perform the ceph commands we
run in the script).
Additionally - the health_services stanza from ceph status has been
removed.
https://www.spinics.net/lists/ceph-devel/msg37767.html
This was not a useful measurement and was removed. This patch removes
that check/metric and adjusts the check to use the "mon_in" metric which
will calculate if the mon is in and up.

[CEPHSTORA-22] Fix MaaS to allow Ceph Luminous support

---

playbooks/vars/main.yml

This reverts commit 25f4a298cb67184026d8e1ef289f07cd19ef8fd6.
Reverted because it breaks support's workflow.

RE-1127 Revert "RE-645 use ansible_hostname..."

---

doc/utils/maas_checks_util.py
doc/utils/requirements.txt

Other half of the fix to maas_checks_util to backport to Python 2.7.
- Pull in pathlib2 if pathlib not available
- f"" -> "".format() or str()
Fixes: TURTLES-321
Cc: @briancurtin
Cc: @major
See-Also: jedsmith/privatecloud-docs@732f0c8c1efc32a4fa16c37d9ae9a9e30081e6bf

maas_checks_util: backport to Python 2.7

---

playbooks/vars/maas-ubuntu.yml

This includes the addition of `gcc` and `python-dev` which are minimally required to compile `pip cryptography` on non-OSA servers.

Include packages required for pip cryptography==1.5 on non-OSA builds

---

playbooks/templates/rax-maas/private_lb_api_check_cinder.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_glance.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_heat_api.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_heat_cfn.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_heat_cloudwatch.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_horizon.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_ironic_api.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_keystone.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_neutron.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_nova.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_octavia.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_swift_access.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_swift_healthcheck.yaml.j2
playbooks/vars/maas-openstack.yml

Ensure `private_lb_api_checks` are enabled on a single node and allow a custom scheme/IP/url to be used instead of being hardcoded to `http://{{ internal_vip_address }}`.

Add customization to private_lb_api_check templates

---

playbooks/maas-openstack-horizon.yml
playbooks/templates/rax-maas/private_lb_ssl_cert_expiry_check.yaml.j2

This check is missing when deploying private network monitoring against a url.

Add missing private ssl certificate expiry check

---

playbooks/maas-restart.yml

This is a temporary workaround to prevent rackspace-monitoring-poller from going out of sync in large environments when the playbooks are ran with a high number of forks. This prevents the need to reach out to the monitoring devs to force a re-sync of the private zone. This has been tested in multiple 200+ node environments and successfully allows all checks to register as intended.

Limit agent restarts preventing pollers from going out of sync

---

playbooks/files/rax-maas/plugins/maas_common.py
tests/user_pike_vars.yml

This change resolves issues with OpenStack checks using insecure ssl
and versionless endpoints.
This also adds a test pike variable file for consistency.

Fix MaaS with Ocata+

---

tox.ini

https://review.openstack.org/#/c/526515/ has merged, so we can
ping osa-test back to master

Remove osa-test pin

---

tests/test.yml

We shouldn't need to install or setup the tigkstack grafana bits unless
we are doing upgrades. As this is causing issues with SNI/SSL on the apt
keys for influxdb we should skip installing this.
A flag is added (defaulting not defined), so that we can easily enable
this for testing downtime on upgrades, setting the
"setup_maas_tigkstack" variable to True.

Add setup_maas_tigkstack var default to False

---

playbooks/vars/maas-tigkstack.yml
tests/test.yml

In #414 we tried making this include conditional, however this playbook
is still being included when run w/ older versions of ansible (1.9.6
as an example).
Instead, we update maas_influxdata_key to have an id and keyserver key.
This allows apt_key to work since it doesn't need to speak to
https://repos.influxdata.com/ directly.  Using ansible's apt_key with
https://repos.influxdata.com/ fails because of SNI and:
1. https://github.com/ansible/ansible/pull/32053/ (not backported to
2.3.2.0)
2. ansible 1.9.6 doesn't seem to support SNI on Trusty (python < 2.7.9)

Update maas_influxdata_key variable

---

playbooks/maas-poller-setup.yml
playbooks/maas-tigkstack-telegraf.yml
playbooks/maas-verify.yml
playbooks/vars/main.yml

This commit adds variables for retries and delays in the verify
playbook. This will allow users to override those values should they
need to.
The impetus for this is deploys into phobos, where it takes longer
than the standard delay for rabbit queues to settle.

RE-1200 Configurable retries for verify

---

playbooks/maas-tigkstack-influxdb.yml

When not using the default keyword for creating the retention
policies inside influx, the shards will use autogen rather then
the created rpc_maas policy. The default keyword is now added
to the custom rpc_maas policy in favor of the autogen

Apply retention policy by default

---

playbooks/files/rax-maas/plugins/process_check_host.py

When doing a process_check_host from run_plugin_in_venv.sh script,
the result ƒor the process check is incorrect as the checking process
itself will checked against. This PR fixed it.

TURTLES-305: Process check won't skip the invoking process

---

playbooks/maas-host-kernel.yml
playbooks/maas-host-network.yml

The conntrack_count check is only installed onto hosts
having nf_conntrack module installed and loaded.
Closes-Bug: RO-3009

Fix conntrack_count check

---

doc/source/usage.rst
playbooks/common-tasks/mysql-db-user.yml
playbooks/files/rax-maas/plugins/rally_performance.py
playbooks/files/rax-maas/rally/plugins/neutron_secgroup_create_update_delete.py
playbooks/files/rax-maas/rally/plugins/swift_customer_container_object_scenario.py
playbooks/files/rax-maas/rally/tasks/cinder.yml
playbooks/files/rax-maas/rally/tasks/glance.yml
playbooks/files/rax-maas/rally/tasks/keystone.yml
playbooks/files/rax-maas/rally/tasks/neutron_ports.yml
playbooks/files/rax-maas/rally/tasks/neutron_secgroups.yml
playbooks/files/rax-maas/rally/tasks/nova.yml
playbooks/files/rax-maas/rally/tasks/nova_cinder.yml
playbooks/files/rax-maas/rally/tasks/swift.yml
playbooks/maas-openstack-rally.yml
playbooks/templates/rax-maas/clouds.yaml.j2
playbooks/templates/rax-maas/rally.conf.j2
playbooks/templates/rax-maas/rally_check.yaml.j2
playbooks/templates/rax-maas/rally_deployment.yaml.j2
playbooks/templates/rax-maas/run_plugin_in_rally_venv.sh.j2
playbooks/vars/maas-rally.yml
tests/test-ansible-functional.sh
tests/test_with_maas_rally.yml
tests/user_ceph_vars.yml
tests/user_master_vars.yml
tests/user_newton_vars.yml
tests/user_ocata_vars.yml
tests/user_pike_vars.yml
tests/user_rpcm_secrets.yml

This commit adds the following:
- Playbook to deploy performance monitoring
- MaaS plugin to execute and manage rally tasks
- A set of performance scenarios
- cinder
- boot instance from local disk
- create volume
- attach volume to instance
- detach volume from instance
- delete volume
- delete instance
- glance
- create image
- delete image
- keystone
- fetch token
- validate token
- neutron_ports
- create port
- delete port
- neutron_secgroups
- create security group
- update security group
- delete security group
- nova
- boot instance from local disk
- delete instance
- nova_cinder
- create cinder volume
- boot instance from volume
- delete instance
- swift
- create container
- upload object
- download object
- delete object
- delete container

Add maas_rally performance monitoring

---

playbooks/maas-openstack-rally.yml

Gating is failing due to flakey behavior from the `openstack quota` command
in the `maas-openstack-rally.yml` playbook.  Based on a conversation with
@cloudnull, the behavior is intermittent and the failure occurs even when
the quota has been set appropriately.
Gating will fail in the verification stage if the quotas aren't actually set.

Unblock gating

---

playbooks/vars/maas-rally.yml

This commit changes the default alarm_consecutive_count for maas_rally from 2
to 3.  This is in line with the default used for other checks.

Set maas_rally default alarm_consecutive_count to 3

---

tests/aio-create.sh

This change replaces the use of the deprecated script run_tests.sh with
gating/post_merge_test/run.

RE-1296 Use rpc-ceph gating script for deployment

---

gating/pre_merge_test/run
run-tests.sh
run_tests.sh
tests/aio-create.sh
tests/test-ansible-functional.sh
tests/test-setup.yml
tox.ini

This change removes support for independent role repository testing now
that it is no longer supported in rpc-gating and rpc-maas has been moved
to using the standard jobs.
The changes made are:
- replacing the use of IRR_CONTEXT with RE_JOB_SCENARIO
- removing run-tests.sh and run_tests.sh
This pull request depends on https://github.com/rcbops/rpc-gating/pull/612

RE-1276 Remove IRR support

---

playbooks/files/rax-maas/plugins/managed_k8_api_local_check.py
playbooks/maas-managed-k8.yml
playbooks/templates/rax-maas/lb_api_check_managed_k8.yaml.j2
playbooks/templates/rax-maas/managed_k8_api_local_check.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_managed_k8.yaml.j2
playbooks/vars/maas-managed-k8.yml

This adds rudimentary checks for the K8 API by reading the endpoints
from the K8 auth DB and parsing them.

K8S-595 Add MaaS check for Kubernetes API to rpc-maas

---

gating/pre_merge_test/run

This change adds support for running the tests currently performed by
Travis CI using the standard jobs provided by the RE team.

RE-1164 Support replacing Travis with rpc-gating

---

playbooks/files/rax-maas/plugins/conntrack_count.py
playbooks/maas-container-all.yml
playbooks/maas-container-conntrack.yml
playbooks/templates/rax-maas/conntrack_count.yaml.j2

Netfilter connection tracking is separately configured per LXC container,
in addition to the netfilter settings of the host OS.
The current MAAS check is changed to add the capability to query
connection tracking statistics from inside the LXC container.
Closes-Bug: TURTLES-289

Adding nf_conntrack monitoring for neutron agent container

---

contrib/maas_rally_influxdb_grafana_dashboard.json
playbooks/files/rax-maas/plugins/rally_performance.py
playbooks/maas-openstack-rally.yml
playbooks/templates/rax-maas/rally_check.yaml.j2
playbooks/templates/rax-maas/rally_config.yaml.j2
playbooks/vars/maas-rally.yml

This commit adds the following:
- Changes to the maas_rally plugin to send performance data to an arbitrary
influxdb endpoint
- A templated grafana dashboard in .json format

Initial commit of rally/influxdb integration

---

playbooks/vars/maas-host.yml

nbd devices get generated once the benchmark tool is run as part of
Ceph. This creates devices that are then automatically picked up. We
shouldn't monitor these.
Whilst the devices are unmapped, the /dev/nbdx devices stay around, and
can't be removed.

CEPHSTORA-116 Exclude nbd devices from disk util checks

---

playbooks/files/tigkstack/maas_telegraf_format.py
playbooks/maas-tigkstack-telegraf.yml
playbooks/templates/tigkstack/maas_telegraf_format.yml.j2
playbooks/vars/maas-tigkstack.yml

Rally plugins should be excluded from execution by telegraf. The TIGK deployment playbooks duplicate each invocation of every plugin. This causes problems especially for rally. 
This change introduces a new config file for the `maas_telegraf_format.py` file which allows a user to define a regex of what to include. By default `.*` is used to maintain current behavior. Excluding the rally plugins is as simple as setting `maas_telegraf_regex_pat: "^(?!rally).*"` In the `/etc/openstack_deploy/user_maas_vars.yml` file and running the `maas-tigkstack-telegraf.yml` playbook.

Add regex to telegraf_format to allow filtering

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

Since Luminous the "overall_status" field in the json output for Ceph
has "HEALTH_WARNING" to alert you to the fact it has changed. With the
following message:
"overall_status":"HEALTH_WARN","detail":["'ceph health' JSON format
has changed in luminous. If you see this your monitoring system is
scraping the wrong fields. Disable this with 'mon health preluminous
compat warning = false'"
We can set the compat warning = false setting, but it would be a better
approach to monitor the correct value.
In order to make this change backwards compatible with Ceph versions
less than Jewel, we will need to use the "overall_status" field when the
"status" field does not exist (e.g. in Jewel).

CEPHSTORA-106 Update ceph_monitoring.py for Luminous

---

playbooks/files/rax-maas/plugins/conntrack_count.py

Some nodes like compute nodes don't necessarily have lxc installed
but the conntrack monitor expect it for container monitoring.
This fix makes the lxc module optional for bare metal conntrack
checks.

Make lxc import optional

---

playbooks/templates/rax-maas/private_ping_check.yaml.j2
playbooks/templates/rax-maas/private_ssh_check.yaml.j2

Allows overridability of period and timeout values for these checks.

[RO-3945] Modify period and timeout overrides to use label instead of check_name

---

playbooks/templates/rax-maas/rally_check.yaml.j2
playbooks/vars/maas-rally.yml

This commit makes the following changes parameterizes the description statistic that is used for alarm criteria.  The default metric also changes from '95pctl' to 'mean', which makes more sense for the default setting of concurrency = 1.

Parameterize statistic used for Rally alarms

---

playbooks/templates/rax-maas/rally_check.yaml.j2

This PR splits the logical warning and critical states into separate
alerts.
A story is required to understand why this is necessary.  Currently, the
process that transform MaaS events into CORE tickets null routes MaaS events
matching the WARNING status.  To work around this, both the logical warning
and critical states were mapped to the MaaS CRITICAL state to ensure a ticket
was generated in CORE.  This ensured support received a ticket and could
investigate.  However, MaaS also does not re-issue an event just because a
status message (i.e. from warning to BREACH) changed, which is a problem
when you need to distinguish between logical warning and critical states for
reporting.
So, after this change we will receive a NEW alert when a metric transitions
from a logical warning state to a …

Split warning and critical to separate alarms

---

playbooks/maas-pre-flight.yml
playbooks/site.yml
tests/user_kilo_vars.yml
tests/user_liberty_vars.yml
tests/user_master_vars.yml
tests/user_mitaka_vars.yml
tests/user_newton_vars.yml
tests/user_ocata_vars.yml
tests/user_pike_vars.yml

This change adds a pre-flight check to ensure all passwords are set
prior to RPC-MaaS being deployed. A new playbook was created which uses
the example password file to iterate and find if any of the passwords
are unset from the playbook runtime. If a required password is missing
the task will produce a failure which instructs the deployer to set the
required password before continuing.
Issue: [RLM-529](https://rpc-openstack.atlassian.net/browse/RLM-529)

[RLM-529] Add pre-flight check to ensure all passwords are set

---

playbooks/files/rax-maas/plugins/octavia_api_local_check.py
playbooks/maas-openstack-octavia.yml

In most installations we will be runnign straight Octavia and hence
Ovtavia V1 AI will be disabled so we need to run checks against
the V2 API.

Switches check to use Octavia V2 API

---

playbooks/files/rax-maas/plugins/rally_performance.py

This change fixes an over-indented block.

Fix overindent in maas_rally plugin

---

playbooks/files/rax-maas/plugins/maas_common.py

The comment referenced a bug that had been abandoned ages ago, and was stating the value for a variable was hard coded to False when it was actually hard coded to True since c967c5e2eab6fd8

Removed old comment

---

playbooks/files/rax-maas/plugins/designate_api_local_check.py
playbooks/files/rax-maas/plugins/designate_mdns_local_check.py
playbooks/maas-openstack-all.yml
playbooks/maas-openstack-designate.yml
playbooks/templates/rax-maas/designate_api_local_check.yaml.j2
playbooks/templates/rax-maas/designate_mdns_local_check.yaml.j2
playbooks/templates/rax-maas/designate_process_check.yaml.j2
playbooks/templates/rax-maas/lb_api_check_designate.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_designate.yaml.j2
playbooks/vars/maas-openstack.yml

Initial commit for monitoring designate services the checks include scripts for performing local checks for the API and the designate-mdns service. Created a template for checking designate service processes but not currently creating a check for those processes.

RI-133: Inital MaaS Commit for Designate

---

playbooks/maas-tigkstack-grafana.yml
playbooks/vars/maas-tigkstack.yml

In ansible 1.9, the URI module requires `requests` python module to add the RPC-MaaS connector to InfluxDB. This change adds pip and requests to the container which allows the grafana playbook to create the connector properly.

Add pip to InfluxDB container for grafana playbook

---

playbooks/files/rax-maas/plugins/rally_performance.py
playbooks/maas-openstack-rally.yml
playbooks/templates/rax-maas/maas_rally.yaml.j2
playbooks/templates/rax-maas/maas_rally_logrotate.j2
playbooks/templates/rax-maas/rally_check.yaml.j2
playbooks/vars/maas-rally.yml
releasenotes/notes/TURTLES-673-ef4f66cdf13e61a0.yaml

This task tracks the following improvements:
```
- Add logging
- Add resiliency to transitory environmental problems
- Automatically recover from stale locks
- Automatically clean up stale resources
```
Some prerequisite refactoring for the items above:
```
- Some information from ansible runtime is required during plugin runtime and was moved to the maas_rally.yml plugin config file:
- Scenario project, username, and password
- Alert thresholds
- Primary resources created by each scenario
- Added a quota factor that each scenario project's quotas are multiplied by.  This allows a scenario to call for cleanup without waiting for cleanup to finish.
- Add alarms for:
- Too many consecutive intervals requiring stale resource cleanup
- Too many consecutive intervals waiting for immature locks …
```

TURTLES-673: Phase 1 maas_rally improvements

---

gating/pre_merge_test/run

The rpc-ceph job is failing because the ansible-playbook is no longer
configured by rpc-maas, and we should fall back to use the rpc-ceph
"ceph-ansible-playbook" binary instead.

CEPHSTORA-168 Fix Ansible reference for rpc-ceph

---

playbooks/files/rax-maas/plugins/nova_api_local_check.py
playbooks/files/rax-maas/plugins/nova_api_metadata_local_check.py
playbooks/templates/rax-maas/nova_api_local_check.yaml.j2
playbooks/templates/rax-maas/nova_api_metadata_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local nova api check.
add ssl support to nova_api_metadata_local_check
* Adding protocol and port option to local nova metadata api check.

TURTLES-313 add ssl support to nova_api_local_check

---

playbooks/files/rax-maas/plugins/keystone_api_local_check.py
playbooks/templates/rax-maas/keystone_api_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local keystone api check.

TURTLES-313 add ssl support to keystone_api_local_check

---

playbooks/files/rax-maas/tools/rally_diag.sh
playbooks/maas-openstack-rally.yml
releasenotes/notes/add-maas_rally-support-helper-b0dded3554299e7e.yaml

This commit adds a `rally_diag.sh` script written by Albert Cardenas to each
utility container.  This script enables support to quickly identify OpenStack
resources created by maas_rally scenarios.
To faciliate listing swift containers without storing the maas_rally user's
credentials, the admin user is now granted the admin role on all projects
created to run maas_rally scenarios.

Add rally_diag.sh support helper script

---

playbooks/files/rax-maas/plugins/cinder_api_local_check.py
playbooks/templates/rax-maas/cinder_api_local_check.yaml.j2
playbooks/vars/main.yml

Adding protocol and port option to local cinder api check.
Removed comment pointing towards an abandoned lp bug.
Renamed local variable in function to be all lower case per pep8 standards.
A first of many commits to fix #TURTLES-313
Signed-off-by: Michael Rice <michael.rice@rackspace.com>

TURTLES-313 Adding protocol and port option to cinder API check

---

playbooks/files/rax-maas/plugins/neutron_api_local_check.py
playbooks/files/rax-maas/plugins/neutron_metadata_local_check.py
playbooks/templates/rax-maas/neutron_api_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local neutron api check.
add ssl support to neutron_metadata_local_check
* Adding protocol and port option to local neutron api check.

TURTLES-313 add ssl support to neutron_api_local_check

---

playbooks/files/rax-maas/plugins/octavia_api_local_check.py
playbooks/templates/rax-maas/octavia_api_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local octavia api check.

TURTLES-313 add ssl support to octavia_api_local_check

---

playbooks/library/ceph_osd_host_facts
playbooks/maas-ceph-osd.yml
playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2

When Ceph OSDs change hosts existing directories may be left in place
which can cause the MaaS plays to setup monitoring against non-existent
OSDs.

CEPHSTORA-163 Get ceph OSD ids via ceph osd tree

---

playbooks/templates/rax-maas/cinder_vg_check.yaml.j2
playbooks/templates/rax-maas/cpu_check.yaml.j2
playbooks/templates/rax-maas/disk_utilisation.yaml.j2
playbooks/templates/rax-maas/galera_check.yaml.j2
playbooks/templates/rax-maas/ironic_capacity_check.yaml.j2
playbooks/templates/rax-maas/memory_check.yaml.j2
playbooks/templates/rax-maas/network_throughput.yaml.j2
playbooks/templates/rax-maas/nova_cloud_stats_check.yaml.j2
playbooks/templates/rax-maas/plugins/rabbitmq_status.py
playbooks/templates/rax-maas/rabbitmq_status.yaml.j2
playbooks/vars/maas-infra.yml
playbooks/vars/maas-openstack.yml

Existing work includes:
- Disable capacitive related alarms by default.
- Remove `aborted_clients` alarm from `galera_check`.
- CDM alarms deploy as disabled except for on `shared-infra_hosts` group.
WIP - Reduce noise of rabbitmq_status alarm trifecta.

TURTLES-700 - Remove NVA alarms and update default thresholds

---

playbooks/files/rax-maas/plugins/heat_api_local_check.py
playbooks/templates/rax-maas/heat_api_local_check.yaml.j2
playbooks/vars/main.yml

* Adding protocol and port option to local heat api check.
Another commit for #TURTLES-313

TURTLES-313 add ssl support to heat_api_local_check

---

playbooks/templates/rax-maas/ceph_cluster_stats.yaml.j2
playbooks/templates/rax-maas/ceph_mon_stats.yaml.j2
playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2
releasenotes/notes/Limit-duplicate-mons-and-rgws-checks-to-the-first-node-of-each-group-90305d7c4a4eb55f.yaml
releasenotes/notes/TURTLES-700-Remove-NVA-alarms-and-update-default-thresholds-a319104c3980a3f7.yaml

Limit `ceph_cluster_stats` and `ceph_mons_stats` checks to `groups['mons'][0]` and `ceph_rgw_stats` to `groups['rgws'][0]` to prevent duplicate alarms on ceph clusters.
This was missed in TURTLES-700, but is part of noise-reduction work.

TURTLES-700 (cont'd):  Limit duplicate mons and rgws checks to the first node of each group

---

playbooks/templates/rax-maas/plugins/rabbitmq_status.py

Occasionally, RabbitMQ responds with missing data for a queue. Currently,
rpc-maas will KeyError out when this happens. This commit defends against
any data that the check needs being missing, and also collapses three
iterations across the queue set down to just one with simplified logic.
Tested in one environment.
Fixes: TURTLES-715

rabbitmq_status: insulate against missing data

---

playbooks/files/rax-maas/plugins/maas_common.py

Sets up backward compatibility with Kilo environments; currently, rpc-maas just
404s in Kilo environments due to changes around how endpoints are handled.
Fixes: TURTLES-694

maas_common: make maas deploy to kilo again

---

playbooks/vars/main.yml
releasenotes/notes/TURTLES-745-update-maas_check_timeout-to-59sec-bcd559e76c7527cf.yaml

Now that timeouts are properly applied to agent.plugin checks, the
`maas_check_timeout` value should be raised from 30s to 59s (1s short of the
period). If not, I suspect that we're going to see a higher percentage of plugin
timeouts as the default value is currently half that of what we have been using
all this time (60s default in rackspace monitoring).
Fixes: TURTLES-745

vars: update maas_check_timeout to 59sec

---

doc/source/config-ref.rst
playbooks/maas-ceph-rgw.yml
playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2
playbooks/vars/maas-ceph.yml
releasenotes/notes/radosgw_civetwebport-409c17bfbbb75373.yaml

The civetweb port defaults to 8080 in ceph-ansible, but we may want to
change this.
This PR allows the var to be specified and adds a config-ref for ceph
vars.

CEPHSTORA-195 Allow civetweb port to be set

---

playbooks/files/rax-maas/plugins/octavia_error_check.py
playbooks/templates/rax-maas/octavia_lb_in_error_check.yaml.j2
releasenotes/releasenotes/notes/add_monitoring_for_lb_in_error-b581a07de66ef9d7.yaml

An LB in ERROR indicates that another service Octavia relies on
(e.g. nova, neutron, glance) didn't fulfill a request by Octavia.
This alerts and allows support to investigate the servcies and
restore them into service as needed.

K8S-850: Add MaaS monitoring for LB in ERROR

---

playbooks/files/rax-maas/plugins/rally_performance.py
playbooks/maas-openstack-rally.yml
playbooks/templates/rax-maas/rally_check.yaml.j2
playbooks/vars/maas-rally.yml
releasenotes/notes/task-args-to-config-b9463d48f8fea224.yaml

This change eases troubleshooting burden by moving scenario configuration items
from the plugin CLI arguments to a configuration file.  This allows operators
to simply run the plugin without first looking up the extra arguments from MaaS
agent configuration files.
- Renamed `extra_vars` dictionary to `task_args`
- Move `times` and `concurrency` variables into the new `task_args` dictionary
- Updated playbooks to account for `times` and `concurrency` moving into
`task_args`
- Update the plugin to read task arguments (e.g. `times`, `concurrency`, and
items previously stored in `extra_vars` like network UUIDS) from the config
file instead of from CLI arguments.

TURTLES-761: Read maas_rally scenario config from file

---

playbooks/vars/maas-rally.yml
releasenotes/notes/pin-rally-openstacksdk-26126927500afe54.yaml

Version 0.12.0 of openstacksdk breaks maas_rally's resource cleanup.  This
change pins openstacksdk<0.12.0 until a newer version fixes the problem.

TURTLES-760: Pin openstacksdk for maas_rally venv

---

playbooks/files/rax-maas/plugins/hp_monitoring.py
releasenotes/notes/TURTLES-769-105ac4ec76e36667.yaml

Properly validate logical volume status if HP volume is encrypted.

TURTLES-769: Add alternate logic in hp_monitoring.py for encrypted volumes

---

playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2
releasenotes/notes/CEPHSTORA-223-18f82d876ee8bc4d.yaml

Revert limiting enablement of rgw checks to first node of group. This was an incorrect assumption as part of the NVA reduction work.

Revert limiting enablement of rgw checks to first node of group

---

playbooks/files/rax-maas/plugins/rally_performance.py
releasenotes/notes/tag_influxdb_database-ed7cf8d9fd13e57d.yaml

This change adds an 'influxdb_database' tag to each maas_rally metric sent to
an influxdb endpoint.  This simplifies routing when the influxdb endpoint is
actually an intermediary that ignores the database specified in the write (e.g.
telegraf's http_listener input plugin).
This enables routing to different influxdb databases in telegraf like this:
```
[[inputs.http_listener]]
service_address = ":8186"
[[outputs.influxdb]]
urls = ["http://localhost:8086"]
database = "telegraf"
[outputs.influxdb.tagdrop]
influxdb_database = ["*"]
[[outputs.influxdb]]
urls = ["http://localhost:8086"]
database = "maas_rally"
tagexclude = ["influxdb_database"]
[ouputs.influxdb.tagpass]
influxdb_database = ["maas_rally"]
```

TURTLES-795: Tag maas_rally metrics with influxdb_database

---

playbooks/files/rax-maas/plugins/rally_performance.py
playbooks/templates/rax-maas/rally_check.yaml.j2
releasenotes/notes/influxdb-error-check-3b4b7734f2f876d7.yaml

This change adds a new metric (influxdb_success) and alarm when maas_rally is
configured to send metrics to an influxdb endpoint.  This makes influxdb write
failures non-fatal so that we still get performance metrics to the MaaS API if
writing to influxdb fails.

TURTLES-785: Add maas_rally metric/alarm for influxdb failures

---

playbooks/maas-openstack-rally.yml
playbooks/vars/maas-rally.yml
tests/aio-create.sh

This change removes maas_rally's dependency on the MaaS virtual environment's
pip requirements and constraints.  The catalyst for this was gating failures
related to the version of python-magnumclient pinned in the standard maas
virtual environment.
Troubleshooting revealed that maas_rally only needed monitorstack from the maas
requirements list.
Itemized changes:
- Remove task to copy pip-constraints.txt during maas_rally venv build
- Remove references to pip-constraints.txt from maas_rally venv build
- Remove references to maas_pip_packages ansible var from maas_rally venv build
- Add monitorstack dependency to maas_rally_pip_packages ansible var
- Swap openstacksdk upper constraint for a keystoneauth1 lower constraint (an
improvement of 551dd6b)

TURTLES-823: Simplify maas_rally pip dependencies & constraints

---

playbooks/templates/rax-maas/octavia_quota_check.yaml.j2
releasenotes/notes/fix-octavia-quota-template-1eff1e297338dc94.yaml

Fix non-quoted metric in Octavia quota template

Fix non-quoted metric in Octavia quota template

---

tests/aio-create.sh

The test execution nodes do not have these packages installed, so
we need to do that for the OSA build to work.

Install required packages before AIO test

---

playbooks/templates/common/macros.jinja
releasenotes/notes/fix_lb_ssl_metadata-cad42e09e426daf9.yaml

Update metadata macro to include lb_ssl_expiry_check and private_lb_ssl_expiry_check in the API category.

Include lb_ssl_expiry_check in the API check category

---

playbooks/files/rax-maas/plugins/managed_k8s_services_local_check.py
playbooks/maas-managed-k8.yml
playbooks/templates/rax-maas/lb_ui_check_k8s.yaml.j2
playbooks/templates/rax-maas/managed_k8s_auth_local_check.yaml.j2
playbooks/templates/rax-maas/managed_k8s_etg_local_check.yaml.j2
playbooks/templates/rax-maas/managed_k8s_etp_local_check.yaml.j2
playbooks/templates/rax-maas/managed_k8s_ui_local_check.yaml.j2
playbooks/templates/rax-maas/mk8s_auth_process_check.yaml.j2
playbooks/templates/rax-maas/mk8s_etg_process_check.yaml.j2
playbooks/templates/rax-maas/mk8s_etp_process_check.yaml.j2
playbooks/templates/rax-maas/mk8s_ui_process_check.yaml.j2
playbooks/templates/rax-maas/private_lb_ui_check_mk8s.yaml.j2
playbooks/vars/maas-managed-k8.yml
playbooks/vars/main.yml
releasenotes/notes/K8S-381_monitor_mk8s_containers-1a478428700d9039.yaml

Adds process checks and (local) api checks.
Note: Since most of the services except ui should not be widely exposed
I am not adding checks for reaching them from the Interweb.

K8S-381 Connect all LXC services (UI/ETS/etc) to RPC-O MaaS

---

doc/utils/README.rst
doc/utils/maas_checks_config.py

Per INTAKERPC-120 and TURTLES-802, this utility needs to be changed to work on Python 2.7 as well as updated to handle newly added checks. Additionally, there was an ask to utilize the categorization that check templates now expose.
This change updates the Jinja undefined handler to work with both Python 2 and Python 3 as well as the necessary changes to stop ignoring some newer checks that we were skipping.
Additionally, the module was renamed slightly so it's easier to talk about both the docs end of this and the rpc-maas end of it.

Update maas_checks_util for Python 2, new checks

---

playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2
releasenotes/notes/ceph_rgw_address-6116f3f9c3906afd.yaml

This PR allows you to use an address for Rados GW that is not the
default ansilbe_host address.
The method utilises the existing ceph-ansible variables to define the
radosgw_address, radosgw_address_block or radosgw_interface, as you
would in ceph-ansible. This is to ensure that ceph-ansible has
configured Rados GW to listen on the same address as we set up MaaS to
monitor against.

CEPHSTORA-304 Allow MaaS to use a different radosgw_address

---

playbooks/files/rax-maas/plugins/neutron_service_check.py
playbooks/files/rax-maas/plugins/nova_service_check.py
playbooks/templates/rax-maas/neutron_dhcp_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_l3_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_linuxbridge_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_metadata_agent_check.yaml.j2
playbooks/templates/rax-maas/neutron_metering_agent_check.yaml.j2
playbooks/templates/rax-maas/nova_cert_check.yaml.j2
playbooks/templates/rax-maas/nova_compute_check.yaml.j2
playbooks/templates/rax-maas/nova_conductor_check.yaml.j2
playbooks/templates/rax-maas/nova_consoleauth_check.yaml.j2
playbooks/templates/rax-maas/nova_scheduler_check.yaml.j2

@npawelek:   As per our conversation,  when the API node can't be reached from agent/computer nodes: https://github.com/rcbops/rpc-maas/blob/master/playbooks/files/rax-maas/plugins/neutron_service_check.py#L35, We generate a warning instead of letting plugin exit(1)

TURTLES-894: WARN neutron/nova agents/computes/schedulers node if can't reach API

---

doc/maas-checks/source/README.rst
doc/maas-checks/source/conf.py
doc/maas-checks/source/maas_checks_plugin.py

To support the need for prose documentation alongside the automated check docs that are rendered, this change introduces a `stubs` directory that includes documentation stubs that are inserted during the build at the appropriate spot for said stub. Each category and check includes a "title.rst" stub file for category and check-wide descriptions to go under their respective titles, and alarm descriptions are named after the alarm.
This includes empty stubs for everything right not that makes a complete build. If stubs are missing for any category, check, or alarm, that will cause the build to emit a warning log, which at current will kill the build. If stubs are empty, which all of them are right now, the build will emit an info message to the log stating that it found no content.

Support category/check/alarm doc descriptions

---

contrib/maas_rally_telegraf_datadog_example.conf
playbooks/files/rax-maas/plugins/rally_performance.py
releasenotes/notes/tag_influxdb_database-ed7cf8d9fd13e57d.yaml

This PR adds an example telegraf -> Datadog configuration snippet to the
contrib/ directory.  This example can be used by deployers who wish to ship
maas_rally performance metrics to Datadog for visualization and analysis.

TURTLES-832: Add example telegraf->Datadog configuration for maas_rally

---

playbooks/maas-openstack-ironic.yml

ironic_all host group doesn't actually include ironic_compute group.  ironic_compute is actually a sub-group for nova_compute.  When installing ironic maas checks,  we will need to "Gather Facts" on ALL ironic related nodes so we will have all necessary ansible variables. 
Reference error:
> TASK [Install ironic ironic-compute checks] ************************************
> task path: /opt/rpc-maas/playbooks/testing-ironic-compute.yml:59
> <aio1_ironic_compute_container-22cda6a6> Because this is a task using "delegate_to" pipelining has been disabled. but will be restored upon completion of this task.
> container_name: "aio1"
> physical_host: "aio1"
> fatal: [aio1_ironic_compute_container-22cda6a6 -> 172.29.236.100]: FAILED! => {"changed": false, "failed": true, "invocation": …

Add ironic compute to ironic gather facts playbook

---

test-requirements.txt
tox.ini

This change adds support for the bandit security static analyzer tool, per https://rpc-openstack.atlassian.net/browse/TURTLES-1017.
This is currently configured to run bandit against any Python code it finds inside the playbooks directory, which is all of the plugin code that the maas checks run. It is additionally configured to ignore two low severity checks that are about the existence of import statements for subprocess and lxml. We use those libraries intentionally, so we don't need to be warned that their introduction to our codebase are potentially vulnerable to issues. Ignoring those two warnings doesn't ignore warnings emitted around specific vulnerabilities found.

Add bandit to tox.ini

---

tox.ini

Bandit currently is not able to output issues at severities lower than what it's configured to run and evaluate pass/fail status of, but we still need to know about those lower severity issues rather than ignore them. Since bandit runs in a matter of seconds, this change runs bandit at the lowest level to get a log of every possible issue, but it ignores the exit code (the leading '-' does this). The second run of bandit runs at the most strict level, and that's what we pass or fail based on.
See https://github.com/PyCQA/bandit/issues/341 for a feature request entered that would remove the need for us to run twice.

Run bandit twice for extra logging

---

playbooks/maas-agent-install.yml
releasenotes/notes/remove-agent-install-maas-vars-file-include-d4efdbc1496308ca.yaml

is redundant and problematic for RPC-R Maas work

Remove - vars/maas-{{ ansible_distribution | lower }}.yml include as it

---

playbooks/maas-openstack-octavia.yml
releasenotes/notes/fix-octavia-rpc-r-register-issue.yaml

https://github.com/rcbops/rpc-maas/blob/master/playbooks/maas-openstack-octavia.yml#L73-L92
It looks like the 'Get project id (RPC-R)' task is overwriting the octavia_project_return
registered variable even when skipped.  This causes the 'Set project id' task to fail on
rpc-o environments as it tries to pull from the stdout of the shell command.  This fix just
sets up a different var and set_fact task for each based on the same conditionals.

JIRA: REO-336 Fix octavia playbook issues due to rpc-r additions

---

playbooks/templates/rax-maas/nova_console_check.yaml.j2
playbooks/vars/maas-openstack.yml
releasenotes/notes/map-nova-console-to-maas-vars-cdbd5bbe6ce4e6e8.yaml

`nova_console_type` is renamed to `maas_nova_console_type`
along with `nova_console_ports` which is also renamed to
`maas_nova_console_ports` in order to prevent variable
inheritance issues deriving from OSA use.

Remove conflicting nova_console_type override

---

tests/maasutils.py

Give click commands explicit names so it doesn't convert underscores to dashes out from under us.

CEPHSTORA-449 Fix underscore to dash issue with click

---

playbooks/files/rax-maas/plugins/maas_common.py
playbooks/maas-pre-flight.yml
playbooks/templates/rax-maas/run_plugin_in_rally_venv.sh.j2
playbooks/templates/rax-maas/run_plugin_in_venv.sh.j2
releasenotes/notes/fixing-maas-rc-absent-checks-cda74b0d92f4e835.yaml

Some 1.7.8 checks (nova api) breaks in absence of maasrc file.  This fix

---

playbooks/files/rax-maas/plugins/maas_common.py
releasenotes/notes/fix-glance-cinder-api-version-issue.yaml

The maas_common.py is setting OS_VOLUME_API_VERSION and
OS_IMAGE_API_VERSION with a default of None.  This caused
calls to get_auth_details to fail a key check for 'None'
causing nova and neutron checks to fail of those variables
are not being set in the environment anywhere.
JIRA: REO-343

Fixes Glance & Cinder API Version Check Issue

---

playbooks/files/rax-maas/plugins/conntrack_count.py
playbooks/templates/rax-maas/conntrack_count.yaml.j2
releasenotes/notes/TURTLES-1006-add-ns-checks-conntack-plugin-5dcd0ff5de96a3b2.yaml

In addition to checking the container root namespace,
nested namespaces inside the container are checked against the
container maximum configured connection tracking count.
Only the highest connection tracking count is reported, as
MAAS limites the number of metrics it can process.
Closes-Bug: TURTLES-1006

Report conntrack count for all namespaces

---

playbooks/files/rax-maas/plugins/nfs_check.py
playbooks/files/rax-maas/tools/rpc-maas-tool.py
playbooks/vars/maas-host.yml
releasenotes/notes/fix-maas-verify-turtles-1516-a34ec4deb64541f2.yaml
tests/aio-create.sh
tests/test-ansible-functional.sh
tests/test.yml
tests/test_with_maas_rally.yml
tests/user_ceph_vars.yml
tests/user_hummingbird_vars.yml
tests/user_kilo_vars.yml
tests/user_liberty_vars.yml
tests/user_master_vars.yml
tests/user_mitaka_vars.yml
tests/user_newton_vars.yml
tests/user_ocata_vars.yml
tests/user_pike_vars.yml
tests/user_queens_vars.yml

Enable the following variables to enable all functionality of maas-verify.yml:
maas_verify_registration (determine if checks and alarms actually registered with the API)
maas_verify_status (determine if there are any active alarms)

TURTLES-1516 Properly enable maas-verify.yml in all situations

---

playbooks/vars/maas-rally.yml
releasenotes/notes/run-tests-rally-fix-ddedf4242415ee2b.yaml

`ansible_host` was missed in the rally vars which resulted in playbook failure. This resolves the issue using the same fix added in the initial PR: #577.

Fix rally vars undefined ansible_host

---

releasenotes/notes/gating_rh_unreg-c44e0064d7a0f24a.yaml
tests/test-ansible-functional.sh

Removed duplication of the RH subscription-unregister by moving it to the gate exit tasks.

Ensure RH subscription is unregistered properly in the gate exit tasks

---

.gitmodules
bootstrap-embedded-ansible.sh
playbooks/generate-environment-vars.yml
releasenotes/notes/INSIGHTS-223-add-mtc-submodule-6c584c96ccc456e9.yaml

This change adds the RPC tooling repository, magnanimous-turbo-chainsaw (MTC), as a submodule of rpc-maas. This repo is intended to provide resources to be shared across the toolstack deployments. As part of the initial commit, a few of the resources have been symlinked into the rpc-maas structure.

INSIGHTS-223 Leverage upstream embedded ansible script

---

playbooks/library/ceph_osd_host_facts
playbooks/maas-ceph-osd.yml
releasenotes/notes/INSIGHTS-306-fix-ceph-facts-module-672b20d9aa508e60.yaml

This was preventing fact gathering from succeeding in non-OSP environments. It was causing the deploy_osp option to always be set.

Add type to deploy_osp option in ceph_osd_host_facts module

---

.gitmodules
bootstrap-embedded-ansible.sh
playbooks/generate-environment-vars.yml

This has essentially been obsoleted with the heavy development to the MTC repo. It doesn't make sense to have it included as a submodule anymore.

Remove MTC submodule

---

playbooks/templates/rax-maas/maasrc.j2

The usage of OS_IMAGE_API_VERSION in maas_common.py was explicitly obtaining the value from environment variables. This change actually exports the values when maasrc is sourced from maas_common.py.

Fix usage of OS_IMAGE_API_VERSION for glance in maas_common.py

---

playbooks/files/rax-maas/plugins/swift-recon.py
tox.ini

modified swift-recon.py so that get_container_name works for both lxc and docker without shell==True so that bandit tests pass
swift-recon.py was raising bandit high sev issues due to us self signing certs and allowing for the possibility of shell injection by running subprocesses with shell set to True.    It was only set up this way so that the container name could be retrieved from a docker ps  command - awking for the swift-proxy container.  In order to resolve this issue, the full list of docker issues was retrieved.  This list of containers was then searched for the entry (if it existed) containing the name swift-proxy.  If found, the container name was returned.  All without having to invoke a subprocess that used shell output.
Also, to resolve the self signed certs issue, we are …

Bandit testing

---

tests/aio-create.sh
tests/test-ansible-functional.sh
tests/user_rpco-liberty_vars.yml
tests/user_rpco-mitaka_vars.yml

Adds the ability to utilize aio-create.sh to create RPCO Liberty or
Mitaka AIO. This is primarily useful to build test servers for
ensuring dynamic variable generation is functioning successfully.

Add RPCO Liberty and Mitaka test scenarios

---

playbooks/files/rax-maas/plugins/hp_monitoring.py
playbooks/files/rax-maas/plugins/openmanage.py
playbooks/templates/rax-maas/hp-check.yaml.j2
playbooks/templates/rax-maas/openmanage-powersupply.yaml.j2

This change leverages HP and Dell hardware management CLI tooling to
include monitoring the power supply status.

NATT-51 Add vendor powersupply monitoring

---

playbooks/files/rax-maas/plugins/iptables_check.py
playbooks/maas-openstack-nova.yml
playbooks/templates/rax-maas/nova_security_group_check.yaml.j2

When the following sysctl parameters are set to 0, instances are not
actively protected by iptables.
/proc/sys/net/bridge/bridge-nf-call-arptables
/proc/sys/net/bridge/bridge-nf-call-ip6tables
/proc/sys/net/bridge/bridge-nf-call-iptables
This change provides functionality to ensure these are set properly
across all compute nodes with instances running.

NATT-63 Ensure security groups are actively enforcing

---

playbooks/maas-infra-tgtd.yml
playbooks/maas-openstack-all.yml
playbooks/templates/common/macros.jinja
playbooks/templates/rax-maas/tgtd_process_check.yaml.j2

This change adds a tgtd process check when service is discovered on
cinder volume and nova compute hosts. If this process is discovered a
process check will be installed which will alert should the process ever
die or become unresponsive.

Add TGTD process check

---

playbooks/files/rax-maas/plugins/nova_service_check.py

nova services can be in different states while also being "enabled". If
the service is set down and is done so via internal nova automation we
will now create an alert.

Update nova service check to alert on additional nova states

---

playbooks/maas-infra-multipathd.yml
playbooks/maas-openstack-all.yml
playbooks/templates/common/macros.jinja
playbooks/templates/rax-maas/multipathd_process_check.yaml.j2

This change adds a multipath check which will now look for the multipath
process and if the process its found, and there are active connections,
a process check will be deployed. This check will alert if the process
dies or ever becomes unresponsive.

Add multipath check

---

playbooks/files/rax-maas/plugins/container_storage_check.py
playbooks/maas-container-storage.yml

This change will ensure that the container is able to do a storage
lookup and determine the filesystem type.
The constraint for container filesystem checks has been removed.

Add block to correct mtab

---

playbooks/files/rax-maas/plugins/network_stats_check.py
playbooks/maas-host-network.yml
playbooks/templates/common/macros.jinja
playbooks/templates/rax-maas/network_stats_check.yaml.j2
playbooks/vars/maas.yml

This check gathers physical network interface receive and transmit errors, sums
all error values, and evaluates based on a rate-over-time function in MaaS. By
default it looks for a total greater than 64 over a 60s period of time.

NATT-83: Add network statistic error rate check

---

playbooks/files/rax-maas/plugins/ironic_compute_nova_service_check.py
playbooks/files/rax-maas/plugins/maas_common.py
playbooks/files/rax-maas/plugins/nova_api_local_check.py
playbooks/files/rax-maas/plugins/nova_cloud_stats.py
playbooks/files/rax-maas/plugins/nova_service_check.py
playbooks/files/rax-maas/plugins/swift-recon.py
playbooks/maas-pre-flight.yml
playbooks/templates/rax-maas/run_plugin_in_rally_venv.sh.j2
playbooks/templates/rax-maas/run_plugin_in_venv.sh.j2
playbooks/vars/maas.yml

This change converts nova client to use the openstacksdk in Kilo
environments. Fixes some nuances around the kilo codename '1andone'
which prevented some dynamic generation aspects from functioning
properly. Includes sourcing /etc/environment in the venv wrapper,
and updates swift-recon.py to allow baremetal proxy deployment.

Update latest codebase for Kilo

---

playbooks/common-tasks/maas-agent-ubuntu-install.yml
playbooks/common-tasks/maas-venv-create.yml
playbooks/maas-pre-flight.yml
playbooks/vars/maas-ubuntu.yml
tests/test-ansible-functional.sh

This change adds a local fact during pre-flight that will detect whether
a host has containers in the inventory. Depending on this fact the
associated packages will be installed properly.

NATT-90: Update virtualenv creation logic

---

playbooks/maas-openstack-cinder.yml
playbooks/maas-pre-flight.yml
playbooks/vars/maas-openstack.yml

This change resolves some assumptions of always deploying cinder backup
when swift is detected in and environment with cinder.

Fix pre-flight cinder backup logic

---

playbooks/maas-openstack-keystone.yml
playbooks/vars/maas.yml
tests/aio-create.sh
tests/user_rpcm_secrets.yml

Removing as this does not appear to be used any longer.

Remove keystone user create for maas

---

playbooks/maas-container-storage.yml
playbooks/templates/rax-maas/mtab_systemd_oneshot.j2

This changes adds a oneshot (run once) systemd unit file to unlink and
re-create /etc/mtab as a regular file. This change allows the container
storage check to properly execute within confines of a chroot in 16.04
and onward.

Recreate /etc/mtab after container boots

---

playbooks/common-tasks/maas-host-vendor-dell.yml
playbooks/files/rax-maas/plugins/ceph_monitoring.py
playbooks/files/rax-maas/plugins/openmanage.py
playbooks/templates/rax-maas/ceph_cluster_stats.yaml.j2
playbooks/templates/rax-maas/ceph_mon_stats.yaml.j2
playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2
playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2

These changes allow for a physical OSP13 reference architecture
deployment with ceph. There were some assumptions and changes beyond
what was available to test within an osp mnaio.

Update for functional non osp-mnaio environment

---

playbooks/maas-pre-flight.yml
playbooks/vars/maas.yml

In the event that OSA and RPCO versions are not identical, this change
uses the OSA version to detect whether or not holland is deployed into a
virtualenv.

Use OSA version to detect holland virtualenv

---

playbooks/files/rax-maas/plugins/conntrack_count.py
playbooks/vars/maas.yml

the neutron ns check has been updated to use the pyroute2 lib instead of
trying to parse shell output. Context managers are now being used to
enter a namespace when present instead of relying on the lxc-attach
command. All extra cruft has been removed from the check.

fix neutron ns check

---

playbooks/common-tasks/maas-venv-create.yml
playbooks/maas-agent-setup.yml

The '--format value' option did not exist in Kilo. This change uses csv
format to identify the keystone endpoint, which also exists in later
versions. Also provides an interface override in-case the internal
interface is v2.

Fix Kilo endpoint detection and venv pip options

---

playbooks/maas-container-conntrack.yml
playbooks/templates/rax-maas/conntrack_count.yaml.j2

This change fixes the conntrack_status check run in the
maas-container-conntrack.yml playbook to prevent overwriting the
physical conntrack_count check. This will create two separate checks with
different names off the same template.

Create additional check name for container_conntrack_count

---

playbooks/maas-pre-flight.yml
playbooks/vars/maas.yml

This change automatically disables known release-specific checks during
an OSP deployment.

Enable release-specific disabled checks for RPCR OSP

---

playbooks/vars/maas.yml
tests/aio-create.sh
tests/test-ansible-functional.sh
tests/user_stein_vars.yml

This change adds the ability to deploy the openstack/openstack-ansible
stable/stein branch within rpc-maas tests.

Add OpenStack Stein including test scenario

---

playbooks/maas-pre-flight.yml

This change alters the proxy detection logic following alterations in
how MTC detects and builds proxy variables utilized by Ansible.

Update maas_proxy_url logic

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py
playbooks/library/ceph_osd_host_facts
playbooks/maas-ceph-osd.yml
playbooks/templates/rax-maas/ceph_osd_stats.yaml.j2

This change refactors the ceph_osd_stats checks to have a 1:1
relationship of checks to alarms. The refactor utilizes the local socket
versus using expensive ceph API calls. Playbooks will also
attempt to remove the legacy osd_stats_check templates including those
with stale OSD IDs.

Refactor ceph osd alarms

---

playbooks/maas-pre-flight.yml
playbooks/maas-remove-old-templates.yml
playbooks/site.yml
playbooks/templates/common/macros.jinja

This change will find check templates that are older than the deployment
date plus 8 hours and move them to a backup directory. This helps to
ensure only checks that should be deployed, are deployed.

Move templates older than deploy date

---

playbooks/library/service_discovery.py

This change modifies the logic around defining the service name to
additionally remove underscores as well as dashes.

Sanitize catalog service names

---

playbooks/maas-poller-setup.yml
playbooks/maas-pre-flight.yml
playbooks/maas-restart.yml
playbooks/templates/rax-maas/rackspace-monitoring-poller.cfg
playbooks/templates/rax-maas/rackspace-monitoring-poller.cfg.j2
playbooks/vars/maas.yml

This changes removes usage of HTTP as the endpoints don't communicate
using HTTP. Instead, when a proxy is defined, we opt to use openssl
directly to determine whether the connection is possible without a
proxy. If this fails it will fallback to defining the maas_proxy_url
variable.

Simplify maas_proxy_url logic

---

playbooks/common-tasks/maas-infra-ubuntu-install.yml
playbooks/common-tasks/maas-venv-create.yml
tests/test-ansible-functional.sh

The most notable change upgrading Ansible from 2.6.12 to 2.7.11 is that
Ansible 2.7+ requires setuptools in order to build an isolated
virtualenv with --no-system-site-packages (default). Our typical OSA
deployments alternatively replace the --index-url with that of the repo
container for all pip related tasks. As setuptools is now required, but
not part of the repo, it will fail. These changes will temporarily
remove the index-url from the pip.conf to successfully build the
virtualenv.

Bump embedded Ansible version to 2.7.11

---

tox.ini

The transition from git.openstack.org to opendev.org has caused some
issues with TLS certificate verification. Since the resources are simply
redirecting, this change attempts to point them at the new location
instead. Also updates PIP_OPTS to include isolated and checkout latest
branch of openstack-ansible-tests.

Change requirements to opendev.org

---

.gitignore
playbooks/files/pip-constraints.txt

This change removes the majority of constraints around packages consumed by monitoring.

Remove pip version constraints

---

playbooks/common-tasks/maas-agent-ubuntu-install.yml
playbooks/common-tasks/maas-poller-ubuntu-install.yml
playbooks/files/rax-maas/tools/rpc-maas-tool.py
playbooks/maas-ceph-raxmon.yml
playbooks/maas-pre-flight.yml
playbooks/templates/common/macros.jinja
playbooks/vars/maas-ubuntu.yml

Added version comparison for ceph authentication as a result of a
customer deployed with ceph Jewel. The mgr auth command is only
accessible in Luminous onward. Added the ability to override apt
certificate validation.

Update ceph auth for jewel

---

playbooks/maas-openstack-all.yml
playbooks/maas-openstack-octavia.yml
playbooks/templates/rax-maas/lb_api_check_octavia.yaml.j2
playbooks/templates/rax-maas/octavia_process_check.yaml.j2
playbooks/templates/rax-maas/private_lb_api_check_octavia.yaml.j2
playbooks/vars/maas-openstack.yml

This change re-enables Octavia playbooks in maas-openstack-all.yml and
ensures the plugins are functionally working. Including commit from BjoernT
removing sanitized Octavia process names.

Re-enable octavia playbooks and ensure functionality

---

playbooks/templates/rax-maas/ceph_rgw_stats.yaml.j2

On standalone builds this previously used ansible_host, but doesn't
catch situations where radosgw is deployed on a storage network that is
not the management network. This will default to radosgw_address before
using ansible_host.

Provide fallback defining rgw address

---

playbooks/library/service_discovery.py
playbooks/maas-sdk-integration.yml

Only perform cinder aspect of service discovery when cinder is detected
in the inventory.

Only perform cinder backend discovery when cinder exists

---

playbooks/maas-verify.yml

@sdhardy ran into this during the Pipedrive upgrade this weekend.  maas-verify.yml doesn't do this currently, so an expired token means you end up need to push /root/.raxrc manually otherwise.  There doesn't seem to be much harm in preemptively doing anytime that it's run in case the token was updated in the YAML files.  He had done that since everyone came to the same conclusion about it being an expired token when everything was showing as failed during a subsequent maas-verify.yml run (after fixing some previously discovered issues).  But we didn't realize the .raxrc file was never updated until I looked directly at what the playbooks were doing (and ending up pushing it via an ad-hoc run to workaround it during the maintenance).
This fixes that.

Add creation of .raxrc during verify to avoid expired token

---

playbooks/files/pip-constraints.txt
playbooks/templates/rax-maas/rally-constraint.txt.j2

The monitorstack on github is moved to opendev.org
and was no longer installable through the old URL

Update monitorstack for new URL

---

playbooks/files/rax-maas/plugins/hp_monitoring.py

In commit 99ee251a4c5c7a60092766d3b9556b69c8cce5a1, function get_hpasmcli_status() was used but it wasn't defined. I changed references to this back to get_chassis_status to get the script working again.

changed hp_monitoring get_hpasmcli_status back to get_chassis_status

---

playbooks/files/rax-maas/plugins/network_stats_check.py
playbooks/templates/rax-maas/network_stats_check.yaml.j2
playbooks/vars/maas.yml

If a softnet backlog is full, it will silently drop packets without any
logged indication of it happening. The second column of
/proc/net/softnet_stats will increment on a per-CPU basis. This
functionality simply sums these values. The threshold has been
configured as 0 because any value for these indicates that the kernel
must be tuned accordingly.
Closes #677

Add functionality for monitoring softnet stats

---

playbooks/library/ceph_osd_host_facts
playbooks/maas-ceph-osd.yml
playbooks/maas-ceph-raxmon.yml
playbooks/maas-pre-flight.yml

These changes allow playbooks to properly execute on OSP environments
with standalone ceph. It effectively prevents the use of Docker
commands when standalone ceph is deployed on baremetal.

Add standlone ceph option for OSP

---

playbooks/files/rax-maas/plugins/network_stats_check.py
playbooks/templates/rax-maas/network_stats_check.yaml.j2
playbooks/vars/maas.yml

This change adds an additional metric for column 3 of
/proc/net/softnet_stat, which indicates an increasing counter for
time_squeeze per CPU. Increasing values indicates that kernel level
network tuning may be needed.

Include time_squeeze in network stats check

---

playbooks/files/rax-maas/plugins/openmanage.py
playbooks/maas-infra-rabbitmq.yml
playbooks/templates/rax-maas/rabbitmq_status.yaml.j2
playbooks/vars/maas-openstack.yml

This change adds some basic introspection to the maas-infra-rabbitmq.yml
playbooks. The latest minor release of OSP13 modified the rabbitmq.config
management section to lock down access explicitly to localhost. Dynamic
inventory cannot be updated as it would break prior releases, and puppet
can't effectively be modified to prevent changes in later OSP releases from
breaking it again.

Add introspection to account for local rabbitmq management address

---

playbooks/files/rax-maas/plugins/hp_monitoring.py
playbooks/templates/rax-maas/hp-check.yaml.j2

This fixes a bug with the hp monitoring plugin which was only detecting
failures associated with logical volumes. When a physical drive is marked
as 'Predictive Failure' with the ssacli command line utility, the status
does not cause the logical volume to degrade. This change separates the
logicaldrive and physical drive metrics to ensure that predictive
failures are also accounted for.

Update hp_monitoring.py to catch predictive failures

---

playbooks/vars/maas.yml

contextlibv2 0.4.0 is getting installed through dependancies into the
maas venv. Its missing the suppress class that is called later on
triggering a failure. Adding this to the maas_pip_packages installs
a later version fixing the issue.

JIRA: RPCOS-51 Fix missing contextlibv2 suppress class

---

playbooks/files/pip-constraints.txt
playbooks/templates/rax-maas/rally-constraint.txt.j2
playbooks/vars/maas.yml

It looks like on 23AUG20 diskcache started with versions 5.0.X.
This breaks the import on python 2 when checking for the 'Disk'
subclass. Locking diskcache down to version 4.1.0 fixes the
issue.

JIRA-33: pip diskcache version issue

---

playbooks/maas-host-vendor.yml

When the director is on a VM, the playbooks look for
a dell or hp vendor check install playbook which doesn't
exist.  The ansible_virtualization_role var will be 'host'
for physical hardware and 'guest' for VMs. I'm using this
to filter out the install of the vendor checks.

JIRA: RPCOS-33 Disable vendor checks for director VM

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

ceph_health_status = ceph_status['health']['overall_status']
is no longer available through ceph status.

Fixing health check for nautilus

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

When installing rpc-maas onto OSP13 using ceph, the ceph_health
check was failing.  It looks like this was due to a breaking
change in PR 702 assuming that either 'overall_status' or
'status' checks exist exclusively. Luminous has both with
'status' being set to 'HEALTH_OK' and 'overall_status' set
to 'HEALTH_WARN' to let users know not to use it.

JIRA: RPCOS-33 Fix ceph_health for luminous

---

playbooks/files/rax-maas/plugins/holland_local_check.py
playbooks/files/rax-maas/plugins/nfs_check.py
playbooks/library/ceph_osd_host_facts

The following findings are keeping the pep8 linter from passing:
* playbooks/files/rax-maas/plugins/nfs_check.py
(:21:1: F401 'metric' imported but unused)
* playbooks/files/rax-maas/plugins/holland_local_check.py
(:67:9: F841 local variable 'lxc_cgroup_stat' is assigned to but never used)
* playbooks/library/ceph_osd_host_facts
(:67:42: E712 comparison to False should be 'if cond is False:' or
'if not cond:')

JIRA RPCOS-33: Fixes for pep8 findings

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

After a meeting with the storage team, it looks like a
quick fix to ignore certain ceph health checks would be
helpful until we can break out things into individual
checks and alarms per type of breakage.

JIRA: REPCOS-44 Ignore some ceph health checks

---

playbooks/files/rax-maas/plugins/octavia_check_quota_limits.py
playbooks/vars/maas-openstack.yml

Octavia does not consume cinder volumes and
the volume check can be removed.
Apart from the issue that the quota check is not scoped to the
actual service tenant, resulting into false alerts.

Remove cinder quota check from octavia plugin

---

playbooks/maas-openstack-octavia.yml
playbooks/maas-openstack-swift.yml
playbooks/vars/main.yml

This applies to keystone calls in the swift and octavia playbooks.

Allow keystone endpoint interface set with keystone_check_interface var.

---

playbooks/maas-openstack-swift.yml
playbooks/templates/rax-maas/private_ping_check.yaml.j2
playbooks/templates/rax-maas/private_ssh_check.yaml.j2

- Swift checks should not be deploying on OSP. The end_play call was
only being done on one play in the playbook.
- The undercloud private checks were failing when the
MAAS_DIRECTOR_NAME env var was set changing the inventory.

Swift and undercloud private fixes.

---

playbooks/files/rax-maas/plugins/iptables_check.py
playbooks/maas-agent-install.yml
playbooks/maas-agent-setup.yml
playbooks/maas-ceph-mon.yml
playbooks/maas-ceph-osd.yml
playbooks/maas-ceph-rgw.yml
playbooks/maas-host-cdm.yml
playbooks/maas-host-kernel.yml
playbooks/maas-host-network.yml
playbooks/maas-host-private-checks.yml
playbooks/maas-host-vendor.yml
playbooks/maas-pre-flight.yml

- The iptables_check.py is now properly reporting the nf-table status
- The Ceph groups are now directly included in the tasks hosts as we
currently do not create a maas/cached inventory, native inventories
from OSA, ceph and OSP are utilized.

Python3 and Ussuri (ceph) fixes

---

playbooks/vars/maas.yml

Pyroute2 does now require mitogen in the latest version.
Without mitogen, import statements fail and the conntrack check
as well

Adding package dependency for pyroute2

---

playbooks/files/rax-maas/plugins/ceph_monitoring.py

In ceph octopus the mon quorum details have been removed from the status output, the mon check simply looks for the local name in the list of mon quorum hosts rather than extract it's rank and check for that rank in the mon quorum list.  The rank is no longer available.
The osdmap data has been flattened in the json output as seen below.  It was [osdmap][osdmap][attributes], but has been flattened in octopus to [osdmap][attributes].
Ticket https://core.rackspace.com/py/ticket/view.pt?ref_no=211222-05538 contains an example alert without this patch applied.
ceph octopus output:
root@1170870-ceph1:/usr/lib/rackspace-monitoring-agent/plugins# ceph status -f json-pretty
{
"fsid": "2bc8eebb-5bad-4988-9319-98ff964d6dde",
"health": {
"status": "HEALTH_OK",
"checks": {},
"mutes": []
}, …

fixes for status output changes in octopus

---

playbooks/files/rax-maas/plugins/maas_common.py
playbooks/vars/maas.yml

platform.linux_distribution has been deprecated completely. similar functionality is available via distro, and distro.name() specifically, for our use case. Appears backward compatible with (at least) py35 on 16.04.

Moves to distro from platform due to deprecation

---

scripts/prepare.sh

The script is checking if the ansible_venv directory exists. We have cases where the venv was present but was created with python2. With this change, the ansible_venv will be recreated if python3 isn't installed.

Check if python3 is installed in the ansible venv

---

playbooks/files/rax-maas/plugins/holland_local_check.py
scripts/prepare.sh

The holland monitoring script checks to see if a container exists by checking if the cgroup path is present:
/sys/fs/cgroup/pids/lxc/<container_name>
In Ubuntu 20.04, the cgroup path has changed to:
/sys/fs/cgroup/pids/lxc.payload.<container_name>
I added a nested try/except so both paths are checked.

Update holland check to support new Ubuntu 20 cgroup path

---

playbooks/files/rax-maas/plugins/openmanage.py

The issue popped up on the Pipedrive Ubuntu 18 to 20 upgrade in FRA. The change has been tested there and related MaaS checks are working with this new version.

Added openmanage 10.1.0.1 to supported versions

---

playbooks/templates/rax-maas/lb_api_check_octavia.yaml.j2

This issue was already fixed in the file octavia_group playbooks/templates/rax-maas/private_lb_api_check_octavia.yaml.j2 by checking and setting the correct group name in a variable:
`{% set octavia_group = groups['octavia-api'][0] |default("") |join(groups['octavia_api'][0] |default("")) %}`
I've updated this template to do the same.

Fix invalid octavia_api groupname
